# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'GetOwnerQueryParams',
    'GetOwnerQueryParamsDict',
    'ListOwnerMembersQueryParams',
    'ListOwnerMembersQueryParamsDict',
    'ListOwnersQueryParams',
    'ListOwnersQueryParamsDict',
]

class GetOwnerQueryParamsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[Mapping[str, _builtins.str]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class GetOwnerQueryParams:
    def __init__(__self__, *,
                 additional_params: Optional[Mapping[str, _builtins.str]] = None):
        """
        Query params for the API request.

        :param Mapping[str, _builtins.str] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: Optional[Mapping[str, _builtins.str]]):
        pulumi.set(self, "additional_params", value)


class ListOwnerMembersQueryParamsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[Mapping[str, _builtins.str]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class ListOwnerMembersQueryParams:
    def __init__(__self__, *,
                 additional_params: Optional[Mapping[str, _builtins.str]] = None):
        """
        Query params for the API request.

        :param Mapping[str, _builtins.str] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: Optional[Mapping[str, _builtins.str]]):
        pulumi.set(self, "additional_params", value)


class ListOwnersQueryParamsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[Mapping[str, _builtins.str]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """
    cursor: NotRequired[_builtins.str]
    """
    The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
    """
    email: NotRequired[Sequence[_builtins.str]]
    """
    Only return workspaces owned by one of the provided email addresses.
    """
    limit: NotRequired[_builtins.int]
    """
    The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
    """
    name: NotRequired[Sequence[_builtins.str]]
    """
    Only return workspaces with one of the provided names. Only exact matches are returned.
    """

@pulumi.input_type
class ListOwnersQueryParams:
    def __init__(__self__, *,
                 additional_params: Optional[Mapping[str, _builtins.str]] = None,
                 cursor: Optional[_builtins.str] = None,
                 email: Optional[Sequence[_builtins.str]] = None,
                 limit: Optional[_builtins.int] = None,
                 name: Optional[Sequence[_builtins.str]] = None):
        """
        Query params for the API request.

        :param Mapping[str, _builtins.str] additional_params: Additional query params to send with the request that are not defined in the API spec.
        :param _builtins.str cursor: The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        :param Sequence[_builtins.str] email: Only return workspaces owned by one of the provided email addresses.
        :param _builtins.int limit: The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        :param Sequence[_builtins.str] name: Only return workspaces with one of the provided names. Only exact matches are returned.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)
        if cursor is not None:
            pulumi.set(__self__, "cursor", cursor)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if limit is None:
            limit = 20
        if limit is not None:
            pulumi.set(__self__, "limit", limit)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: Optional[Mapping[str, _builtins.str]]):
        pulumi.set(self, "additional_params", value)

    @_builtins.property
    @pulumi.getter
    def cursor(self) -> Optional[_builtins.str]:
        """
        The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        """
        return pulumi.get(self, "cursor")

    @cursor.setter
    def cursor(self, value: Optional[_builtins.str]):
        pulumi.set(self, "cursor", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> Optional[Sequence[_builtins.str]]:
        """
        Only return workspaces owned by one of the provided email addresses.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter
    def limit(self) -> Optional[_builtins.int]:
        """
        The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        """
        return pulumi.get(self, "limit")

    @limit.setter
    def limit(self, value: Optional[_builtins.int]):
        pulumi.set(self, "limit", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[Sequence[_builtins.str]]:
        """
        Only return workspaces with one of the provided names. Only exact matches are returned.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "name", value)


