// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.CronJobs
{
    [RenderResourceType("render:cron-jobs:RunCronJob")]
    public partial class RunCronJob : global::Pulumi.CustomResource
    {
        /// <summary>
        /// user who cancelled the cron job run
        /// </summary>
        [Output("canceledBy")]
        public Output<string?> CanceledBy { get; private set; } = null!;

        [Output("finishedAt")]
        public Output<string?> FinishedAt { get; private set; } = null!;

        [Output("startedAt")]
        public Output<string?> StartedAt { get; private set; } = null!;

        [Output("status")]
        public Output<Pulumi.Render.CronJobs.Status> Status { get; private set; } = null!;

        /// <summary>
        /// user who triggered the cron job run
        /// </summary>
        [Output("triggeredBy")]
        public Output<string?> TriggeredBy { get; private set; } = null!;


        /// <summary>
        /// Create a RunCronJob resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RunCronJob(string name, RunCronJobArgs? args = null, CustomResourceOptions? options = null)
            : base("render:cron-jobs:RunCronJob", name, args ?? new RunCronJobArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RunCronJob(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("render:cron-jobs:RunCronJob", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-render",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RunCronJob resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RunCronJob Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RunCronJob(name, id, options);
        }
    }

    public sealed class RunCronJobArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the cron job
        /// </summary>
        [Input("cronJobId")]
        public Input<string>? CronJobId { get; set; }

        public RunCronJobArgs()
        {
        }
        public static new RunCronJobArgs Empty => new RunCronJobArgs();
    }
}
