// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getServiceNotificationOverride(args: GetServiceNotificationOverrideArgs, opts?: pulumi.InvokeOptions): Promise<outputs.notificationsettings.GetServiceNotificationOverrideProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("render:notification-settings:getServiceNotificationOverride", {
        "serviceId": args.serviceId,
    }, opts);
}

export interface GetServiceNotificationOverrideArgs {
    /**
     * The ID of the service
     */
    serviceId: string;
}
export function getServiceNotificationOverrideOutput(args: GetServiceNotificationOverrideOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.notificationsettings.GetServiceNotificationOverrideProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("render:notification-settings:getServiceNotificationOverride", {
        "serviceId": args.serviceId,
    }, opts);
}

export interface GetServiceNotificationOverrideOutputArgs {
    /**
     * The ID of the service
     */
    serviceId: pulumi.Input<string>;
}
