// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listNotificationOverrides(args?: ListNotificationOverridesArgs, opts?: pulumi.InvokeOptions): Promise<ListNotificationOverridesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("render:notification-settings:listNotificationOverrides", {
    }, opts);
}

export interface ListNotificationOverridesArgs {
}

export interface ListNotificationOverridesResult {
    readonly items: outputs.notificationsettings.NotificationOverrideWithCursor[];
}
export function listNotificationOverridesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListNotificationOverridesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("render:notification-settings:listNotificationOverrides", {
    }, opts);
}

