archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make gen generate_schema
    - make build
builds:
  - binary: pulumi-resource-render
    main: ./cmd/pulumi-resource-render/
    dir: provider
    env:
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/cloudy-sky-software/pulumi-render/provider/pkg/version.Version={{.Tag }}
    overrides:
      - goos: darwin
        goarch: amd64
        goamd64: v1
        goarm: ""
        gomips: ""
        env:
          - CGO_ENABLED=1
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
