# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = ['EnvGroupSecretFileArgs', 'EnvGroupSecretFile']

@pulumi.input_type
class EnvGroupSecretFileArgs:
    def __init__(__self__, *,
                 content: Optional[pulumi.Input[_builtins.str]] = None,
                 env_group_id: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_file_name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a EnvGroupSecretFile resource.
        """
        if content is not None:
            pulumi.set(__self__, "content", content)
        if env_group_id is not None:
            pulumi.set(__self__, "env_group_id", env_group_id)
        if secret_file_name is not None:
            pulumi.set(__self__, "secret_file_name", secret_file_name)

    @_builtins.property
    @pulumi.getter
    def content(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter(name="envGroupId")
    def env_group_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "env_group_id")

    @env_group_id.setter
    def env_group_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "env_group_id", value)

    @_builtins.property
    @pulumi.getter(name="secretFileName")
    def secret_file_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "secret_file_name")

    @secret_file_name.setter
    def secret_file_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secret_file_name", value)


@pulumi.type_token("render:env-groups:EnvGroupSecretFile")
class EnvGroupSecretFile(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 content: Optional[pulumi.Input[_builtins.str]] = None,
                 env_group_id: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_file_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a EnvGroupSecretFile resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[EnvGroupSecretFileArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a EnvGroupSecretFile resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param EnvGroupSecretFileArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EnvGroupSecretFileArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 content: Optional[pulumi.Input[_builtins.str]] = None,
                 env_group_id: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_file_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EnvGroupSecretFileArgs.__new__(EnvGroupSecretFileArgs)

            __props__.__dict__["content"] = content
            __props__.__dict__["env_group_id"] = env_group_id
            __props__.__dict__["secret_file_name"] = secret_file_name
            __props__.__dict__["created_at"] = None
            __props__.__dict__["env_vars"] = None
            __props__.__dict__["environment_id"] = None
            __props__.__dict__["name"] = None
            __props__.__dict__["owner_id"] = None
            __props__.__dict__["secret_files"] = None
            __props__.__dict__["service_links"] = None
            __props__.__dict__["updated_at"] = None
        super(EnvGroupSecretFile, __self__).__init__(
            'render:env-groups:EnvGroupSecretFile',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'EnvGroupSecretFile':
        """
        Get an existing EnvGroupSecretFile resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EnvGroupSecretFileArgs.__new__(EnvGroupSecretFileArgs)

        __props__.__dict__["content"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["env_vars"] = None
        __props__.__dict__["environment_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["owner_id"] = None
        __props__.__dict__["secret_files"] = None
        __props__.__dict__["service_links"] = None
        __props__.__dict__["updated_at"] = None
        return EnvGroupSecretFile(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def content(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="envVars")
    def env_vars(self) -> pulumi.Output[Optional[Sequence['outputs.EnvVar']]]:
        return pulumi.get(self, "env_vars")

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="ownerId")
    def owner_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "owner_id")

    @_builtins.property
    @pulumi.getter(name="secretFiles")
    def secret_files(self) -> pulumi.Output[Optional[Sequence['outputs.SecretFile']]]:
        return pulumi.get(self, "secret_files")

    @_builtins.property
    @pulumi.getter(name="serviceLinks")
    def service_links(self) -> pulumi.Output[Optional[Sequence['outputs.EnvGroupLink']]]:
        """
        List of serviceIds linked to the envGroup
        """
        return pulumi.get(self, "service_links")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "updated_at")

