// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class Service extends pulumi.CustomResource {
    /**
     * Get an existing Service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Service {
        return new Service(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'render:services:Service';

    /**
     * Returns true if the given object is an instance of Service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Service.__pulumiType;
    }

    /**
     * Defaults to "yes"
     */
    public readonly autoDeploy!: pulumi.Output<enums.services.AutoDeploy | undefined>;
    /**
     * If left empty, this will fall back to the default branch of the repository
     */
    public readonly branch!: pulumi.Output<string | undefined>;
    public readonly buildFilter!: pulumi.Output<outputs.services.BuildFilter | undefined>;
    public /*out*/ readonly deployId!: pulumi.Output<string | undefined>;
    public readonly envVars!: pulumi.Output<(outputs.services.EnvVarKeyValue | outputs.services.EnvVarKeyGenerateValue)[] | undefined>;
    public readonly image!: pulumi.Output<outputs.services.Image | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly ownerId!: pulumi.Output<string>;
    /**
     * Do not include the branch in the repo string. You can instead supply a 'branch' parameter.
     */
    public readonly repo!: pulumi.Output<string | undefined>;
    public readonly rootDir!: pulumi.Output<string | undefined>;
    public readonly secretFiles!: pulumi.Output<outputs.services.SecretFile[] | undefined>;
    public /*out*/ readonly service!: pulumi.Output<outputs.services.Service | undefined>;
    public readonly serviceDetails!: pulumi.Output<outputs.services.StaticSiteDetails | outputs.services.WebServiceDetails | outputs.services.PrivateServiceDetails | outputs.services.BackgroundWorkerDetails | outputs.services.CronJobDetails | undefined>;
    public readonly type!: pulumi.Output<enums.services.Type>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.ownerId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ownerId'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["autoDeploy"] = (args ? args.autoDeploy : undefined) ?? "yes";
            resourceInputs["branch"] = args ? args.branch : undefined;
            resourceInputs["buildFilter"] = args ? args.buildFilter : undefined;
            resourceInputs["envVars"] = args ? args.envVars : undefined;
            resourceInputs["image"] = args ? args.image : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ownerId"] = args ? args.ownerId : undefined;
            resourceInputs["repo"] = args ? args.repo : undefined;
            resourceInputs["rootDir"] = args ? args.rootDir : undefined;
            resourceInputs["secretFiles"] = args ? args.secretFiles : undefined;
            resourceInputs["serviceDetails"] = args ? args.serviceDetails : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["deployId"] = undefined /*out*/;
            resourceInputs["service"] = undefined /*out*/;
        } else {
            resourceInputs["autoDeploy"] = undefined /*out*/;
            resourceInputs["branch"] = undefined /*out*/;
            resourceInputs["buildFilter"] = undefined /*out*/;
            resourceInputs["deployId"] = undefined /*out*/;
            resourceInputs["envVars"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["ownerId"] = undefined /*out*/;
            resourceInputs["repo"] = undefined /*out*/;
            resourceInputs["rootDir"] = undefined /*out*/;
            resourceInputs["secretFiles"] = undefined /*out*/;
            resourceInputs["service"] = undefined /*out*/;
            resourceInputs["serviceDetails"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Service.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    /**
     * Defaults to "yes"
     */
    autoDeploy?: pulumi.Input<enums.services.AutoDeploy>;
    /**
     * If left empty, this will fall back to the default branch of the repository
     */
    branch?: pulumi.Input<string>;
    buildFilter?: pulumi.Input<inputs.services.BuildFilterArgs>;
    envVars?: pulumi.Input<pulumi.Input<inputs.services.EnvVarKeyValueArgs | inputs.services.EnvVarKeyGenerateValueArgs>[]>;
    image?: pulumi.Input<inputs.services.ImageArgs>;
    name?: pulumi.Input<string>;
    ownerId: pulumi.Input<string>;
    /**
     * Do not include the branch in the repo string. You can instead supply a 'branch' parameter.
     */
    repo?: pulumi.Input<string>;
    rootDir?: pulumi.Input<string>;
    secretFiles?: pulumi.Input<pulumi.Input<inputs.services.SecretFileArgs>[]>;
    serviceDetails?: pulumi.Input<inputs.services.StaticSiteDetailsArgs | inputs.services.WebServiceDetailsArgs | inputs.services.PrivateServiceDetailsArgs | inputs.services.BackgroundWorkerDetailsArgs | inputs.services.CronJobDetailsArgs>;
    type: pulumi.Input<enums.services.Type>;
}
