# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'Paths1logs1streams1resource17BresourceId7Dgetresponses200contentapplication1jsonschema',
]

@pulumi.output_type
class Paths1logs1streams1resource17BresourceId7Dgetresponses200contentapplication1jsonschema(dict):
    """
    Resource log stream overrides
    """
    def __init__(__self__, *,
                 endpoint: Optional[str] = None,
                 resource_id: Optional[str] = None,
                 setting: Optional['Paths1logs1streams1resource17BresourceId7Dgetresponses200contentapplication1jsonschemaSetting'] = None):
        """
        Resource log stream overrides
        :param str endpoint: The endpoint to stream logs to. Must be present if setting is send. Cannot be present if setting is drop.
        :param str resource_id: The ID of the resource.
        :param 'Paths1logs1streams1resource17BresourceId7Dgetresponses200contentapplication1jsonschemaSetting' setting: Whether to send logs or drop them.
        """
        if endpoint is not None:
            pulumi.set(__self__, "endpoint", endpoint)
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if setting is not None:
            pulumi.set(__self__, "setting", setting)

    @property
    @pulumi.getter
    def endpoint(self) -> Optional[str]:
        """
        The endpoint to stream logs to. Must be present if setting is send. Cannot be present if setting is drop.
        """
        return pulumi.get(self, "endpoint")

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> Optional[str]:
        """
        The ID of the resource.
        """
        return pulumi.get(self, "resource_id")

    @property
    @pulumi.getter
    def setting(self) -> Optional['Paths1logs1streams1resource17BresourceId7Dgetresponses200contentapplication1jsonschemaSetting']:
        """
        Whether to send logs or drop them.
        """
        return pulumi.get(self, "setting")


