// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package keyvalue

import (
	"context"
	"reflect"

	"errors"
	"github.com/cloudy-sky-software/pulumi-render/sdk/go/render/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Input type for creating a Key Value instance
type KeyValue struct {
	pulumi.CustomResourceState

	// The creation time of the Key Value instance
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The ID of the environment the Key Value instance is associated with
	EnvironmentId pulumi.StringPtrOutput `pulumi:"environmentId"`
	// The IP allow list for the Key Value instance
	IpAllowList CidrBlockAndDescriptionArrayOutput        `pulumi:"ipAllowList"`
	Maintenance RedisDetailpropertiesmaintenancePtrOutput `pulumi:"maintenance"`
	// The eviction policy for the Key Value instance
	MaxmemoryPolicy MaxmemoryPolicyPtrOutput `pulumi:"maxmemoryPolicy"`
	// The name of the Key Value instance
	Name pulumi.StringOutput `pulumi:"name"`
	// Options for a Key Value instance
	Options KeyValueOptionsOutput `pulumi:"options"`
	Owner   OwnerOutput           `pulumi:"owner"`
	// The ID of the owner of the Key Value instance
	OwnerId pulumi.StringOutput `pulumi:"ownerId"`
	Plan    PlanOutput          `pulumi:"plan"`
	// Defaults to "oregon"
	Region RegionOutput `pulumi:"region"`
	Status StatusOutput `pulumi:"status"`
	// The last updated time of the Key Value instance
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The version of Key Value
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewKeyValue registers a new resource with the given unique name, arguments, and options.
func NewKeyValue(ctx *pulumi.Context,
	name string, args *KeyValueArgs, opts ...pulumi.ResourceOption) (*KeyValue, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OwnerId == nil {
		return nil, errors.New("invalid value for required argument 'OwnerId'")
	}
	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KeyValue
	err := ctx.RegisterResource("render:key-value:KeyValue", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKeyValue gets an existing KeyValue resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKeyValue(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KeyValueState, opts ...pulumi.ResourceOption) (*KeyValue, error) {
	var resource KeyValue
	err := ctx.ReadResource("render:key-value:KeyValue", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KeyValue resources.
type keyValueState struct {
}

type KeyValueState struct {
}

func (KeyValueState) ElementType() reflect.Type {
	return reflect.TypeOf((*keyValueState)(nil)).Elem()
}

type keyValueArgs struct {
	EnvironmentId *string                   `pulumi:"environmentId"`
	IpAllowList   []CidrBlockAndDescription `pulumi:"ipAllowList"`
	// The eviction policy for the Key Value instance
	MaxmemoryPolicy *MaxmemoryPolicy `pulumi:"maxmemoryPolicy"`
	// The name of the Key Value instance
	Name *string `pulumi:"name"`
	// The ID of the owner of the Key Value instance
	OwnerId string `pulumi:"ownerId"`
	Plan    Plan   `pulumi:"plan"`
	// The region where the Key Value instance is located
	Region *string `pulumi:"region"`
}

// The set of arguments for constructing a KeyValue resource.
type KeyValueArgs struct {
	EnvironmentId pulumi.StringPtrInput
	IpAllowList   CidrBlockAndDescriptionArrayInput
	// The eviction policy for the Key Value instance
	MaxmemoryPolicy MaxmemoryPolicyPtrInput
	// The name of the Key Value instance
	Name pulumi.StringPtrInput
	// The ID of the owner of the Key Value instance
	OwnerId pulumi.StringInput
	Plan    PlanInput
	// The region where the Key Value instance is located
	Region pulumi.StringPtrInput
}

func (KeyValueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*keyValueArgs)(nil)).Elem()
}

type KeyValueInput interface {
	pulumi.Input

	ToKeyValueOutput() KeyValueOutput
	ToKeyValueOutputWithContext(ctx context.Context) KeyValueOutput
}

func (*KeyValue) ElementType() reflect.Type {
	return reflect.TypeOf((**KeyValue)(nil)).Elem()
}

func (i *KeyValue) ToKeyValueOutput() KeyValueOutput {
	return i.ToKeyValueOutputWithContext(context.Background())
}

func (i *KeyValue) ToKeyValueOutputWithContext(ctx context.Context) KeyValueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KeyValueOutput)
}

type KeyValueOutput struct{ *pulumi.OutputState }

func (KeyValueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KeyValue)(nil)).Elem()
}

func (o KeyValueOutput) ToKeyValueOutput() KeyValueOutput {
	return o
}

func (o KeyValueOutput) ToKeyValueOutputWithContext(ctx context.Context) KeyValueOutput {
	return o
}

// The creation time of the Key Value instance
func (o KeyValueOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyValue) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The ID of the environment the Key Value instance is associated with
func (o KeyValueOutput) EnvironmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KeyValue) pulumi.StringPtrOutput { return v.EnvironmentId }).(pulumi.StringPtrOutput)
}

// The IP allow list for the Key Value instance
func (o KeyValueOutput) IpAllowList() CidrBlockAndDescriptionArrayOutput {
	return o.ApplyT(func(v *KeyValue) CidrBlockAndDescriptionArrayOutput { return v.IpAllowList }).(CidrBlockAndDescriptionArrayOutput)
}

func (o KeyValueOutput) Maintenance() RedisDetailpropertiesmaintenancePtrOutput {
	return o.ApplyT(func(v *KeyValue) RedisDetailpropertiesmaintenancePtrOutput { return v.Maintenance }).(RedisDetailpropertiesmaintenancePtrOutput)
}

// The eviction policy for the Key Value instance
func (o KeyValueOutput) MaxmemoryPolicy() MaxmemoryPolicyPtrOutput {
	return o.ApplyT(func(v *KeyValue) MaxmemoryPolicyPtrOutput { return v.MaxmemoryPolicy }).(MaxmemoryPolicyPtrOutput)
}

// The name of the Key Value instance
func (o KeyValueOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyValue) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Options for a Key Value instance
func (o KeyValueOutput) Options() KeyValueOptionsOutput {
	return o.ApplyT(func(v *KeyValue) KeyValueOptionsOutput { return v.Options }).(KeyValueOptionsOutput)
}

func (o KeyValueOutput) Owner() OwnerOutput {
	return o.ApplyT(func(v *KeyValue) OwnerOutput { return v.Owner }).(OwnerOutput)
}

// The ID of the owner of the Key Value instance
func (o KeyValueOutput) OwnerId() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyValue) pulumi.StringOutput { return v.OwnerId }).(pulumi.StringOutput)
}

func (o KeyValueOutput) Plan() PlanOutput {
	return o.ApplyT(func(v *KeyValue) PlanOutput { return v.Plan }).(PlanOutput)
}

// Defaults to "oregon"
func (o KeyValueOutput) Region() RegionOutput {
	return o.ApplyT(func(v *KeyValue) RegionOutput { return v.Region }).(RegionOutput)
}

func (o KeyValueOutput) Status() StatusOutput {
	return o.ApplyT(func(v *KeyValue) StatusOutput { return v.Status }).(StatusOutput)
}

// The last updated time of the Key Value instance
func (o KeyValueOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyValue) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The version of Key Value
func (o KeyValueOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *KeyValue) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KeyValueInput)(nil)).Elem(), &KeyValue{})
	pulumi.RegisterOutputType(KeyValueOutput{})
}
