// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Services.Outputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    [OutputType]
    public sealed class JobQueryParams
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        public readonly Outputs.JobCreateQueryParams? Create;
        /// <summary>
        /// Query params for the read operation.
        /// </summary>
        public readonly Outputs.JobReadQueryParams? Read;

        [OutputConstructor]
        private JobQueryParams(
            Outputs.JobCreateQueryParams? create,

            Outputs.JobReadQueryParams? read)
        {
            Create = create;
            Read = read;
        }
    }
}
