// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Services.Outputs
{

    [OutputType]
    public sealed class StaticSiteDetailsCreate
    {
        public readonly string? BuildCommand;
        public readonly ImmutableArray<Outputs.HeaderCreate> Headers;
        /// <summary>
        /// Defaults to "public"
        /// </summary>
        public readonly string? PublishPath;
        /// <summary>
        /// Defaults to "no"
        /// </summary>
        public readonly Pulumi.Render.Services.StaticSiteDetailsCreatePullRequestPreviewsEnabled? PullRequestPreviewsEnabled;
        public readonly ImmutableArray<Outputs.Route> Routes;
        public readonly string? Type;

        [OutputConstructor]
        private StaticSiteDetailsCreate(
            string? buildCommand,

            ImmutableArray<Outputs.HeaderCreate> headers,

            string? publishPath,

            Pulumi.Render.Services.StaticSiteDetailsCreatePullRequestPreviewsEnabled? pullRequestPreviewsEnabled,

            ImmutableArray<Outputs.Route> routes,

            string? type)
        {
            BuildCommand = buildCommand;
            Headers = headers;
            PublishPath = publishPath;
            PullRequestPreviewsEnabled = pullRequestPreviewsEnabled;
            Routes = routes;
            Type = type;
        }
    }
}
