// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Services.Outputs
{

    /// <summary>
    /// A service header object
    /// </summary>
    [OutputType]
    public sealed class StaticSiteServiceHeader
    {
        public readonly string Name;
        public readonly string Path;
        public readonly string Value;

        [OutputConstructor]
        private StaticSiteServiceHeader(
            string name,

            string path,

            string value)
        {
            Name = name;
            Path = path;
            Value = value;
        }
    }
}
