# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'GetBandwidthSourcePropertiesDataItemPropertiesLabelsPropertiesTrafficSource',
]


@pulumi.type_token("render:metrics:GetBandwidthSourcePropertiesDataItemPropertiesLabelsPropertiesTrafficSource")
class GetBandwidthSourcePropertiesDataItemPropertiesLabelsPropertiesTrafficSource(_builtins.str, Enum):
    TOTAL = "total"
    HTTP = "http"
    WEBSOCKET = "websocket"
    NAT = "nat"
    PRIVATELINK = "privatelink"
