// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Blueprints.Outputs
{

    [OutputType]
    public sealed class GetBlueprintPropertiesResourcesItemProperties
    {
        public readonly string Id;
        public readonly string Name;
        /// <summary>
        /// type of the resource (ex. web_service or postgres)
        /// </summary>
        public readonly Pulumi.Render.Blueprints.GetBlueprintPropertiesResourcesItemPropertiesType Type;

        [OutputConstructor]
        private GetBlueprintPropertiesResourcesItemProperties(
            string id,

            string name,

            Pulumi.Render.Blueprints.GetBlueprintPropertiesResourcesItemPropertiesType type)
        {
            Id = id;
            Name = name;
            Type = type;
        }
    }
}
