# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import builtins
from enum import Enum

__all__ = [
    'BackgroundWorkerDetailsCreateEnv',
    'BackgroundWorkerDetailsCreatePlan',
    'BackgroundWorkerDetailsCreatePullRequestPreviewsEnabled',
    'BackgroundWorkerDetailsCreateRegion',
    'BackgroundWorkerDetailsCreateRuntime',
    'BackgroundWorkerDetailsOutputBuildPlan',
    'BackgroundWorkerDetailsOutputEnv',
    'BackgroundWorkerDetailsOutputPlan',
    'BackgroundWorkerDetailsOutputPullRequestPreviewsEnabled',
    'BackgroundWorkerDetailsOutputRegion',
    'BackgroundWorkerDetailsOutputRuntime',
    'CancelJobStatus',
    'ClearCache',
    'CronJobDetailsCreateEnv',
    'CronJobDetailsCreatePlan',
    'CronJobDetailsCreateRegion',
    'CronJobDetailsCreateRuntime',
    'CronJobDetailsOutputBuildPlan',
    'CronJobDetailsOutputEnv',
    'CronJobDetailsOutputPlan',
    'CronJobDetailsOutputRegion',
    'CronJobDetailsOutputRuntime',
    'CustomDomainDomainType',
    'CustomDomainVerificationStatus',
    'DeployStatus',
    'DeployTrigger',
    'JobStatus',
    'Plan',
    'PreviewsGeneration',
    'PrivateServiceDetailsCreateEnv',
    'PrivateServiceDetailsCreatePlan',
    'PrivateServiceDetailsCreatePullRequestPreviewsEnabled',
    'PrivateServiceDetailsCreateRegion',
    'PrivateServiceDetailsCreateRuntime',
    'PrivateServiceDetailsOutputBuildPlan',
    'PrivateServiceDetailsOutputEnv',
    'PrivateServiceDetailsOutputPlan',
    'PrivateServiceDetailsOutputPullRequestPreviewsEnabled',
    'PrivateServiceDetailsOutputRegion',
    'PrivateServiceDetailsOutputRuntime',
    'RegistryCredentialRegistry',
    'RouteCreateType',
    'RouteType',
    'ServerPortProtocol',
    'ServiceAutoDeploy',
    'ServiceCreateAutoDeploy',
    'ServiceNotifyOnFail',
    'ServiceSuspended',
    'ServiceSuspendersItem',
    'StaticSiteDetailsCreatePullRequestPreviewsEnabled',
    'StaticSiteDetailsOutputBuildPlan',
    'StaticSiteDetailsOutputPullRequestPreviewsEnabled',
    'Status',
    'Trigger',
    'Type',
    'WebServiceDetailsCreateEnv',
    'WebServiceDetailsCreatePlan',
    'WebServiceDetailsCreatePullRequestPreviewsEnabled',
    'WebServiceDetailsCreateRegion',
    'WebServiceDetailsCreateRuntime',
    'WebServiceDetailsOutputBuildPlan',
    'WebServiceDetailsOutputEnv',
    'WebServiceDetailsOutputPlan',
    'WebServiceDetailsOutputPullRequestPreviewsEnabled',
    'WebServiceDetailsOutputRegion',
    'WebServiceDetailsOutputRuntime',
]


class BackgroundWorkerDetailsCreateEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class BackgroundWorkerDetailsCreatePlan(builtins.str, Enum):
    """
    Defaults to "starter"
    """
    STARTER = "starter"
    STANDARD = "standard"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"


class BackgroundWorkerDetailsCreatePullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class BackgroundWorkerDetailsCreateRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class BackgroundWorkerDetailsCreateRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class BackgroundWorkerDetailsOutputBuildPlan(builtins.str, Enum):
    STARTER = "starter"
    PERFORMANCE = "performance"


class BackgroundWorkerDetailsOutputEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class BackgroundWorkerDetailsOutputPlan(builtins.str, Enum):
    """
    The instance type to use for the preview instance. Note that base services with any paid instance type can't create preview instances with the `free` instance type.
    """
    STARTER = "starter"
    STARTER_PLUS = "starter_plus"
    STANDARD = "standard"
    STANDARD_PLUS = "standard_plus"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"
    FREE = "free"
    CUSTOM = "custom"


class BackgroundWorkerDetailsOutputPullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class BackgroundWorkerDetailsOutputRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class BackgroundWorkerDetailsOutputRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class CancelJobStatus(builtins.str, Enum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELED = "canceled"


class ClearCache(builtins.str, Enum):
    """
    If `clear`, Render clears the service's build cache before deploying. This can be useful if you're experiencing issues with your build.
    """
    CLEAR = "clear"
    DO_NOT_CLEAR = "do_not_clear"


class CronJobDetailsCreateEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class CronJobDetailsCreatePlan(builtins.str, Enum):
    """
    Defaults to "starter"
    """
    STARTER = "starter"
    STANDARD = "standard"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"


class CronJobDetailsCreateRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class CronJobDetailsCreateRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class CronJobDetailsOutputBuildPlan(builtins.str, Enum):
    STARTER = "starter"
    PERFORMANCE = "performance"


class CronJobDetailsOutputEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class CronJobDetailsOutputPlan(builtins.str, Enum):
    """
    The instance type to use for the preview instance. Note that base services with any paid instance type can't create preview instances with the `free` instance type.
    """
    STARTER = "starter"
    STARTER_PLUS = "starter_plus"
    STANDARD = "standard"
    STANDARD_PLUS = "standard_plus"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"
    FREE = "free"
    CUSTOM = "custom"


class CronJobDetailsOutputRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class CronJobDetailsOutputRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class CustomDomainDomainType(builtins.str, Enum):
    APEX = "apex"
    SUBDOMAIN = "subdomain"


class CustomDomainVerificationStatus(builtins.str, Enum):
    VERIFIED = "verified"
    UNVERIFIED = "unverified"


class DeployStatus(builtins.str, Enum):
    CREATED = "created"
    BUILD_IN_PROGRESS = "build_in_progress"
    UPDATE_IN_PROGRESS = "update_in_progress"
    LIVE = "live"
    DEACTIVATED = "deactivated"
    BUILD_FAILED = "build_failed"
    UPDATE_FAILED = "update_failed"
    CANCELED = "canceled"
    PRE_DEPLOY_IN_PROGRESS = "pre_deploy_in_progress"
    PRE_DEPLOY_FAILED = "pre_deploy_failed"


class DeployTrigger(builtins.str, Enum):
    API = "api"
    BLUEPRINT_SYNC = "blueprint_sync"
    DEPLOY_HOOK = "deploy_hook"
    DEPLOYED_BY_RENDER = "deployed_by_render"
    MANUAL = "manual"
    OTHER = "other"
    NEW_COMMIT = "new_commit"
    ROLLBACK = "rollback"
    SERVICE_RESUMED = "service_resumed"
    SERVICE_UPDATED = "service_updated"


class JobStatus(builtins.str, Enum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELED = "canceled"


class Plan(builtins.str, Enum):
    """
    The instance type to use for the preview instance. Note that base services with any paid instance type can't create preview instances with the `free` instance type.
    """
    STARTER = "starter"
    STARTER_PLUS = "starter_plus"
    STANDARD = "standard"
    STANDARD_PLUS = "standard_plus"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"
    FREE = "free"
    CUSTOM = "custom"


class PreviewsGeneration(builtins.str, Enum):
    """
    Defaults to "off"
    """
    OFF = "off"
    MANUAL = "manual"
    AUTOMATIC = "automatic"


class PrivateServiceDetailsCreateEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class PrivateServiceDetailsCreatePlan(builtins.str, Enum):
    """
    Defaults to "starter"
    """
    STARTER = "starter"
    STANDARD = "standard"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"


class PrivateServiceDetailsCreatePullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class PrivateServiceDetailsCreateRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class PrivateServiceDetailsCreateRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class PrivateServiceDetailsOutputBuildPlan(builtins.str, Enum):
    STARTER = "starter"
    PERFORMANCE = "performance"


class PrivateServiceDetailsOutputEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class PrivateServiceDetailsOutputPlan(builtins.str, Enum):
    """
    The instance type to use for the preview instance. Note that base services with any paid instance type can't create preview instances with the `free` instance type.
    """
    STARTER = "starter"
    STARTER_PLUS = "starter_plus"
    STANDARD = "standard"
    STANDARD_PLUS = "standard_plus"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"
    FREE = "free"
    CUSTOM = "custom"


class PrivateServiceDetailsOutputPullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class PrivateServiceDetailsOutputRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class PrivateServiceDetailsOutputRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class RegistryCredentialRegistry(builtins.str, Enum):
    """
    The registry to use this credential with
    """
    GITHUB = "GITHUB"
    GITLAB = "GITLAB"
    DOCKER = "DOCKER"
    GOOGLE_ARTIFACT = "GOOGLE_ARTIFACT"
    AWS_ECR = "AWS_ECR"


class RouteCreateType(builtins.str, Enum):
    REDIRECT = "redirect"
    REWRITE = "rewrite"


class RouteType(builtins.str, Enum):
    REDIRECT = "redirect"
    REWRITE = "rewrite"


class ServerPortProtocol(builtins.str, Enum):
    TCP = "TCP"
    UDP = "UDP"


class ServiceAutoDeploy(builtins.str, Enum):
    YES = "yes"
    NO = "no"


class ServiceCreateAutoDeploy(builtins.str, Enum):
    YES = "yes"
    NO = "no"


class ServiceNotifyOnFail(builtins.str, Enum):
    DEFAULT = "default"
    NOTIFY = "notify"
    IGNORE = "ignore"


class ServiceSuspended(builtins.str, Enum):
    SUSPENDED = "suspended"
    NOT_SUSPENDED = "not_suspended"


class ServiceSuspendersItem(builtins.str, Enum):
    ADMIN = "admin"
    BILLING = "billing"
    USER = "user"
    PARENT_SERVICE = "parent_service"
    UNKNOWN = "unknown"


class StaticSiteDetailsCreatePullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class StaticSiteDetailsOutputBuildPlan(builtins.str, Enum):
    STARTER = "starter"
    PERFORMANCE = "performance"


class StaticSiteDetailsOutputPullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class Status(builtins.str, Enum):
    CREATED = "created"
    BUILD_IN_PROGRESS = "build_in_progress"
    UPDATE_IN_PROGRESS = "update_in_progress"
    LIVE = "live"
    DEACTIVATED = "deactivated"
    BUILD_FAILED = "build_failed"
    UPDATE_FAILED = "update_failed"
    CANCELED = "canceled"
    PRE_DEPLOY_IN_PROGRESS = "pre_deploy_in_progress"
    PRE_DEPLOY_FAILED = "pre_deploy_failed"


class Trigger(builtins.str, Enum):
    API = "api"
    BLUEPRINT_SYNC = "blueprint_sync"
    DEPLOY_HOOK = "deploy_hook"
    DEPLOYED_BY_RENDER = "deployed_by_render"
    MANUAL = "manual"
    OTHER = "other"
    NEW_COMMIT = "new_commit"
    ROLLBACK = "rollback"
    SERVICE_RESUMED = "service_resumed"
    SERVICE_UPDATED = "service_updated"


class Type(builtins.str, Enum):
    REDIRECT = "redirect"
    REWRITE = "rewrite"


class WebServiceDetailsCreateEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class WebServiceDetailsCreatePlan(builtins.str, Enum):
    """
    Defaults to "starter"
    """
    STARTER = "starter"
    STANDARD = "standard"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"


class WebServiceDetailsCreatePullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class WebServiceDetailsCreateRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class WebServiceDetailsCreateRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class WebServiceDetailsOutputBuildPlan(builtins.str, Enum):
    STARTER = "starter"
    PERFORMANCE = "performance"


class WebServiceDetailsOutputEnv(builtins.str, Enum):
    """
    This field has been deprecated, runtime should be used in its place.
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"


class WebServiceDetailsOutputPlan(builtins.str, Enum):
    """
    The instance type to use for the preview instance. Note that base services with any paid instance type can't create preview instances with the `free` instance type.
    """
    STARTER = "starter"
    STARTER_PLUS = "starter_plus"
    STANDARD = "standard"
    STANDARD_PLUS = "standard_plus"
    PRO = "pro"
    PRO_PLUS = "pro_plus"
    PRO_MAX = "pro_max"
    PRO_ULTRA = "pro_ultra"
    FREE = "free"
    CUSTOM = "custom"


class WebServiceDetailsOutputPullRequestPreviewsEnabled(builtins.str, Enum):
    """
    This field has been deprecated. previews.generation should be used in its place.
    """
    YES = "yes"
    NO = "no"


class WebServiceDetailsOutputRegion(builtins.str, Enum):
    """
    Defaults to "oregon"
    """
    FRANKFURT = "frankfurt"
    OREGON = "oregon"
    OHIO = "ohio"
    SINGAPORE = "singapore"
    VIRGINIA = "virginia"


class WebServiceDetailsOutputRuntime(builtins.str, Enum):
    """
    Runtime
    """
    DOCKER = "docker"
    ELIXIR = "elixir"
    GO = "go"
    NODE = "node"
    PYTHON = "python"
    RUBY = "ruby"
    RUST = "rust"
    IMAGE = "image"
