// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Metrics
{
    public static class GetBandwidthSource
    {
        public static Task<GetBandwidthSourceResult> InvokeAsync(GetBandwidthSourceArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBandwidthSourceResult>("render:metrics:getBandwidthSource", args ?? new GetBandwidthSourceArgs(), options.WithDefaults());

        public static Output<GetBandwidthSourceResult> Invoke(GetBandwidthSourceInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBandwidthSourceResult>("render:metrics:getBandwidthSource", args ?? new GetBandwidthSourceInvokeArgs(), options.WithDefaults());

        public static Output<GetBandwidthSourceResult> Invoke(GetBandwidthSourceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetBandwidthSourceResult>("render:metrics:getBandwidthSource", args ?? new GetBandwidthSourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBandwidthSourceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Inputs.GetBandwidthSourceQueryParams? QueryParams { get; set; }

        public GetBandwidthSourceArgs()
        {
        }
        public static new GetBandwidthSourceArgs Empty => new GetBandwidthSourceArgs();
    }

    public sealed class GetBandwidthSourceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Input<Inputs.GetBandwidthSourceQueryParamsArgs>? QueryParams { get; set; }

        public GetBandwidthSourceInvokeArgs()
        {
        }
        public static new GetBandwidthSourceInvokeArgs Empty => new GetBandwidthSourceInvokeArgs();
    }


    [OutputType]
    public sealed class GetBandwidthSourceResult
    {
        public readonly ImmutableArray<Outputs.GetBandwidthSourcePropertiesDataItemProperties> Data;

        [OutputConstructor]
        private GetBandwidthSourceResult(ImmutableArray<Outputs.GetBandwidthSourcePropertiesDataItemProperties> data)
        {
            Data = data;
        }
    }
}
