// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package services

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-render/sdk/go/render/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListServices(ctx *pulumi.Context, args *ListServicesArgs, opts ...pulumi.InvokeOption) (*ListServicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListServicesResult
	err := ctx.Invoke("render:services:listServices", args.Defaults(), &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListServicesArgs struct {
	// Query params to send with the API request.
	QueryParams *ListServicesQueryParams `pulumi:"queryParams"`
}

// Defaults sets the appropriate defaults for ListServicesArgs
func (val *ListServicesArgs) Defaults() *ListServicesArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.QueryParams = tmp.QueryParams.Defaults()

	return &tmp
}

type ListServicesResult struct {
	Items []ListServicesResponse `pulumi:"items"`
}

func ListServicesOutput(ctx *pulumi.Context, args ListServicesOutputArgs, opts ...pulumi.InvokeOption) ListServicesResultOutput {
	outputArgs := pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) *ListServicesArgs {
			args := v.(ListServicesArgs)
			return args.Defaults()
		})
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("render:services:listServices", outputArgs, ListServicesResultOutput{}, options).(ListServicesResultOutput)
}

type ListServicesOutputArgs struct {
	// Query params to send with the API request.
	QueryParams ListServicesQueryParamsPtrInput `pulumi:"queryParams"`
}

func (ListServicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServicesArgs)(nil)).Elem()
}

type ListServicesResultOutput struct{ *pulumi.OutputState }

func (ListServicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServicesResult)(nil)).Elem()
}

func (o ListServicesResultOutput) ToListServicesResultOutput() ListServicesResultOutput {
	return o
}

func (o ListServicesResultOutput) ToListServicesResultOutputWithContext(ctx context.Context) ListServicesResultOutput {
	return o
}

func (o ListServicesResultOutput) Items() ListServicesResponseArrayOutput {
	return o.ApplyT(func(v ListServicesResult) []ListServicesResponse { return v.Items }).(ListServicesResponseArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ListServicesResultOutput{})
}
