// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package envgroups

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-render/sdk/go/render/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListEnvGroups(ctx *pulumi.Context, args *ListEnvGroupsArgs, opts ...pulumi.InvokeOption) (*ListEnvGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListEnvGroupsResult
	err := ctx.Invoke("render:env-groups:listEnvGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListEnvGroupsArgs struct {
}

type ListEnvGroupsResult struct {
	Items []EnvGroupMeta `pulumi:"items"`
}

func ListEnvGroupsOutput(ctx *pulumi.Context, args ListEnvGroupsOutputArgs, opts ...pulumi.InvokeOption) ListEnvGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListEnvGroupsResultOutput, error) {
			args := v.(ListEnvGroupsArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv ListEnvGroupsResult
			secret, err := ctx.InvokePackageRaw("render:env-groups:listEnvGroups", args, &rv, "", opts...)
			if err != nil {
				return ListEnvGroupsResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(ListEnvGroupsResultOutput)
			if secret {
				return pulumi.ToSecret(output).(ListEnvGroupsResultOutput), nil
			}
			return output, nil
		}).(ListEnvGroupsResultOutput)
}

type ListEnvGroupsOutputArgs struct {
}

func (ListEnvGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListEnvGroupsArgs)(nil)).Elem()
}

type ListEnvGroupsResultOutput struct{ *pulumi.OutputState }

func (ListEnvGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListEnvGroupsResult)(nil)).Elem()
}

func (o ListEnvGroupsResultOutput) ToListEnvGroupsResultOutput() ListEnvGroupsResultOutput {
	return o
}

func (o ListEnvGroupsResultOutput) ToListEnvGroupsResultOutputWithContext(ctx context.Context) ListEnvGroupsResultOutput {
	return o
}

func (o ListEnvGroupsResultOutput) Items() EnvGroupMetaArrayOutput {
	return o.ApplyT(func(v ListEnvGroupsResult) []EnvGroupMeta { return v.Items }).(EnvGroupMetaArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ListEnvGroupsResultOutput{})
}
