# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'EnvironmentCreateQueryParamsArgs',
    'EnvironmentCreateQueryParamsArgsDict',
    'EnvironmentDeleteQueryParamsArgs',
    'EnvironmentDeleteQueryParamsArgsDict',
    'EnvironmentQueryParamsArgs',
    'EnvironmentQueryParamsArgsDict',
    'EnvironmentReadQueryParamsArgs',
    'EnvironmentReadQueryParamsArgsDict',
    'EnvironmentUpdateQueryParamsArgs',
    'EnvironmentUpdateQueryParamsArgsDict',
    'GetEnvironmentQueryParams',
    'GetEnvironmentQueryParamsDict',
    'ListEnvironmentsQueryParams',
    'ListEnvironmentsQueryParamsDict',
    'ResourcesToEnvironmentCreateQueryParamsArgs',
    'ResourcesToEnvironmentCreateQueryParamsArgsDict',
    'ResourcesToEnvironmentQueryParamsArgs',
    'ResourcesToEnvironmentQueryParamsArgsDict',
]

class EnvironmentCreateQueryParamsArgsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class EnvironmentCreateQueryParamsArgs:
    def __init__(__self__, *,
                 additional_params: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Query params for the API request.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_params", value)


class EnvironmentDeleteQueryParamsArgsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class EnvironmentDeleteQueryParamsArgs:
    def __init__(__self__, *,
                 additional_params: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Query params for the API request.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_params", value)


class EnvironmentQueryParamsArgsDict(TypedDict):
    """
    Query params for each of the operations of the resource.
    """
    create: NotRequired[pulumi.Input[Optional['EnvironmentCreateQueryParamsArgsDict']]]
    """
    Query params for the create operation.
    """
    delete: NotRequired[pulumi.Input[Optional['EnvironmentDeleteQueryParamsArgsDict']]]
    """
    Query params for the delete operation.
    """
    read: NotRequired[pulumi.Input[Optional['EnvironmentReadQueryParamsArgsDict']]]
    """
    Query params for the read operation.
    """
    update: NotRequired[pulumi.Input[Optional['EnvironmentUpdateQueryParamsArgsDict']]]
    """
    Query params for the update operation.
    """

@pulumi.input_type
class EnvironmentQueryParamsArgs:
    def __init__(__self__, *,
                 create: pulumi.Input[Optional['EnvironmentCreateQueryParamsArgs']] = None,
                 delete: pulumi.Input[Optional['EnvironmentDeleteQueryParamsArgs']] = None,
                 read: pulumi.Input[Optional['EnvironmentReadQueryParamsArgs']] = None,
                 update: pulumi.Input[Optional['EnvironmentUpdateQueryParamsArgs']] = None):
        """
        Query params for each of the operations of the resource.

        :param pulumi.Input['EnvironmentCreateQueryParamsArgs'] create: Query params for the create operation.
        :param pulumi.Input['EnvironmentDeleteQueryParamsArgs'] delete: Query params for the delete operation.
        :param pulumi.Input['EnvironmentReadQueryParamsArgs'] read: Query params for the read operation.
        :param pulumi.Input['EnvironmentUpdateQueryParamsArgs'] update: Query params for the update operation.
        """
        if create is not None:
            pulumi.set(__self__, "create", create)
        if delete is not None:
            pulumi.set(__self__, "delete", delete)
        if read is not None:
            pulumi.set(__self__, "read", read)
        if update is not None:
            pulumi.set(__self__, "update", update)

    @_builtins.property
    @pulumi.getter
    def create(self) -> pulumi.Input[Optional['EnvironmentCreateQueryParamsArgs']]:
        """
        Query params for the create operation.
        """
        return pulumi.get(self, "create")

    @create.setter
    def create(self, value: pulumi.Input[Optional['EnvironmentCreateQueryParamsArgs']]):
        pulumi.set(self, "create", value)

    @_builtins.property
    @pulumi.getter
    def delete(self) -> pulumi.Input[Optional['EnvironmentDeleteQueryParamsArgs']]:
        """
        Query params for the delete operation.
        """
        return pulumi.get(self, "delete")

    @delete.setter
    def delete(self, value: pulumi.Input[Optional['EnvironmentDeleteQueryParamsArgs']]):
        pulumi.set(self, "delete", value)

    @_builtins.property
    @pulumi.getter
    def read(self) -> pulumi.Input[Optional['EnvironmentReadQueryParamsArgs']]:
        """
        Query params for the read operation.
        """
        return pulumi.get(self, "read")

    @read.setter
    def read(self, value: pulumi.Input[Optional['EnvironmentReadQueryParamsArgs']]):
        pulumi.set(self, "read", value)

    @_builtins.property
    @pulumi.getter
    def update(self) -> pulumi.Input[Optional['EnvironmentUpdateQueryParamsArgs']]:
        """
        Query params for the update operation.
        """
        return pulumi.get(self, "update")

    @update.setter
    def update(self, value: pulumi.Input[Optional['EnvironmentUpdateQueryParamsArgs']]):
        pulumi.set(self, "update", value)


class EnvironmentReadQueryParamsArgsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class EnvironmentReadQueryParamsArgs:
    def __init__(__self__, *,
                 additional_params: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Query params for the API request.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_params", value)


class EnvironmentUpdateQueryParamsArgsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class EnvironmentUpdateQueryParamsArgs:
    def __init__(__self__, *,
                 additional_params: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Query params for the API request.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_params", value)


class GetEnvironmentQueryParamsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[Mapping[str, _builtins.str]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class GetEnvironmentQueryParams:
    def __init__(__self__, *,
                 additional_params: Optional[Mapping[str, _builtins.str]] = None):
        """
        Query params for the API request.

        :param Mapping[str, _builtins.str] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: Optional[Mapping[str, _builtins.str]]):
        pulumi.set(self, "additional_params", value)


class ListEnvironmentsQueryParamsDict(TypedDict):
    """
    Query params for the API request.
    """
    project_id: Sequence[_builtins.str]
    """
    Filter for resources that belong to a project
    """
    additional_params: NotRequired[Mapping[str, _builtins.str]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """
    created_after: NotRequired[_builtins.str]
    """
    Filter for resources created after a certain time (specified as an ISO 8601 timestamp)
    """
    created_before: NotRequired[_builtins.str]
    """
    Filter for resources created before a certain time (specified as an ISO 8601 timestamp)
    """
    cursor: NotRequired[_builtins.str]
    """
    The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
    """
    environment_id: NotRequired[Sequence[_builtins.str]]
    """
    Filter for resources that belong to an environment
    """
    limit: NotRequired[_builtins.int]
    """
    The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
    """
    name: NotRequired[Sequence[_builtins.str]]
    """
    Filter by name
    """
    owner_id: NotRequired[Sequence[_builtins.str]]
    """
    The ID of the workspaces to return resources for
    """
    updated_after: NotRequired[_builtins.str]
    """
    Filter for resources updated after a certain time (specified as an ISO 8601 timestamp)
    """
    updated_before: NotRequired[_builtins.str]
    """
    Filter for resources updated before a certain time (specified as an ISO 8601 timestamp)
    """

@pulumi.input_type
class ListEnvironmentsQueryParams:
    def __init__(__self__, *,
                 project_id: Sequence[_builtins.str],
                 additional_params: Optional[Mapping[str, _builtins.str]] = None,
                 created_after: Optional[_builtins.str] = None,
                 created_before: Optional[_builtins.str] = None,
                 cursor: Optional[_builtins.str] = None,
                 environment_id: Optional[Sequence[_builtins.str]] = None,
                 limit: Optional[_builtins.int] = None,
                 name: Optional[Sequence[_builtins.str]] = None,
                 owner_id: Optional[Sequence[_builtins.str]] = None,
                 updated_after: Optional[_builtins.str] = None,
                 updated_before: Optional[_builtins.str] = None):
        """
        Query params for the API request.

        :param Sequence[_builtins.str] project_id: Filter for resources that belong to a project
        :param Mapping[str, _builtins.str] additional_params: Additional query params to send with the request that are not defined in the API spec.
        :param _builtins.str created_after: Filter for resources created after a certain time (specified as an ISO 8601 timestamp)
        :param _builtins.str created_before: Filter for resources created before a certain time (specified as an ISO 8601 timestamp)
        :param _builtins.str cursor: The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        :param Sequence[_builtins.str] environment_id: Filter for resources that belong to an environment
        :param _builtins.int limit: The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        :param Sequence[_builtins.str] name: Filter by name
        :param Sequence[_builtins.str] owner_id: The ID of the workspaces to return resources for
        :param _builtins.str updated_after: Filter for resources updated after a certain time (specified as an ISO 8601 timestamp)
        :param _builtins.str updated_before: Filter for resources updated before a certain time (specified as an ISO 8601 timestamp)
        """
        pulumi.set(__self__, "project_id", project_id)
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)
        if created_after is not None:
            pulumi.set(__self__, "created_after", created_after)
        if created_before is not None:
            pulumi.set(__self__, "created_before", created_before)
        if cursor is not None:
            pulumi.set(__self__, "cursor", cursor)
        if environment_id is not None:
            pulumi.set(__self__, "environment_id", environment_id)
        if limit is None:
            limit = 20
        if limit is not None:
            pulumi.set(__self__, "limit", limit)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if owner_id is not None:
            pulumi.set(__self__, "owner_id", owner_id)
        if updated_after is not None:
            pulumi.set(__self__, "updated_after", updated_after)
        if updated_before is not None:
            pulumi.set(__self__, "updated_before", updated_before)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Sequence[_builtins.str]:
        """
        Filter for resources that belong to a project
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Sequence[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: Optional[Mapping[str, _builtins.str]]):
        pulumi.set(self, "additional_params", value)

    @_builtins.property
    @pulumi.getter(name="createdAfter")
    def created_after(self) -> Optional[_builtins.str]:
        """
        Filter for resources created after a certain time (specified as an ISO 8601 timestamp)
        """
        return pulumi.get(self, "created_after")

    @created_after.setter
    def created_after(self, value: Optional[_builtins.str]):
        pulumi.set(self, "created_after", value)

    @_builtins.property
    @pulumi.getter(name="createdBefore")
    def created_before(self) -> Optional[_builtins.str]:
        """
        Filter for resources created before a certain time (specified as an ISO 8601 timestamp)
        """
        return pulumi.get(self, "created_before")

    @created_before.setter
    def created_before(self, value: Optional[_builtins.str]):
        pulumi.set(self, "created_before", value)

    @_builtins.property
    @pulumi.getter
    def cursor(self) -> Optional[_builtins.str]:
        """
        The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        """
        return pulumi.get(self, "cursor")

    @cursor.setter
    def cursor(self, value: Optional[_builtins.str]):
        pulumi.set(self, "cursor", value)

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> Optional[Sequence[_builtins.str]]:
        """
        Filter for resources that belong to an environment
        """
        return pulumi.get(self, "environment_id")

    @environment_id.setter
    def environment_id(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "environment_id", value)

    @_builtins.property
    @pulumi.getter
    def limit(self) -> Optional[_builtins.int]:
        """
        The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        """
        return pulumi.get(self, "limit")

    @limit.setter
    def limit(self, value: Optional[_builtins.int]):
        pulumi.set(self, "limit", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[Sequence[_builtins.str]]:
        """
        Filter by name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="ownerId")
    def owner_id(self) -> Optional[Sequence[_builtins.str]]:
        """
        The ID of the workspaces to return resources for
        """
        return pulumi.get(self, "owner_id")

    @owner_id.setter
    def owner_id(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "owner_id", value)

    @_builtins.property
    @pulumi.getter(name="updatedAfter")
    def updated_after(self) -> Optional[_builtins.str]:
        """
        Filter for resources updated after a certain time (specified as an ISO 8601 timestamp)
        """
        return pulumi.get(self, "updated_after")

    @updated_after.setter
    def updated_after(self, value: Optional[_builtins.str]):
        pulumi.set(self, "updated_after", value)

    @_builtins.property
    @pulumi.getter(name="updatedBefore")
    def updated_before(self) -> Optional[_builtins.str]:
        """
        Filter for resources updated before a certain time (specified as an ISO 8601 timestamp)
        """
        return pulumi.get(self, "updated_before")

    @updated_before.setter
    def updated_before(self, value: Optional[_builtins.str]):
        pulumi.set(self, "updated_before", value)


class ResourcesToEnvironmentCreateQueryParamsArgsDict(TypedDict):
    """
    Query params for the API request.
    """
    additional_params: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    Additional query params to send with the request that are not defined in the API spec.
    """

@pulumi.input_type
class ResourcesToEnvironmentCreateQueryParamsArgs:
    def __init__(__self__, *,
                 additional_params: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Query params for the API request.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] additional_params: Additional query params to send with the request that are not defined in the API spec.
        """
        if additional_params is not None:
            pulumi.set(__self__, "additional_params", additional_params)

    @_builtins.property
    @pulumi.getter(name="additionalParams")
    def additional_params(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Additional query params to send with the request that are not defined in the API spec.
        """
        return pulumi.get(self, "additional_params")

    @additional_params.setter
    def additional_params(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_params", value)


class ResourcesToEnvironmentQueryParamsArgsDict(TypedDict):
    """
    Query params for each of the operations of the resource.
    """
    create: NotRequired[pulumi.Input[Optional['ResourcesToEnvironmentCreateQueryParamsArgsDict']]]
    """
    Query params for the create operation.
    """

@pulumi.input_type
class ResourcesToEnvironmentQueryParamsArgs:
    def __init__(__self__, *,
                 create: pulumi.Input[Optional['ResourcesToEnvironmentCreateQueryParamsArgs']] = None):
        """
        Query params for each of the operations of the resource.

        :param pulumi.Input['ResourcesToEnvironmentCreateQueryParamsArgs'] create: Query params for the create operation.
        """
        if create is not None:
            pulumi.set(__self__, "create", create)

    @_builtins.property
    @pulumi.getter
    def create(self) -> pulumi.Input[Optional['ResourcesToEnvironmentCreateQueryParamsArgs']]:
        """
        Query params for the create operation.
        """
        return pulumi.get(self, "create")

    @create.setter
    def create(self, value: pulumi.Input[Optional['ResourcesToEnvironmentCreateQueryParamsArgs']]):
        pulumi.set(self, "create", value)


