// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("render");

/**
 * The Render API key
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey");
    },
    enumerable: true,
});

/**
 * When a service is updated, a deployment is automatically triggered. This variable controls whether or not the service cache should be cleared upon deployment.
 */
export declare const clearCacheOnServiceUpdateDeployments: enums.services.DeployClearCache | undefined;
Object.defineProperty(exports, "clearCacheOnServiceUpdateDeployments", {
    get() {
        return __config.getObject<enums.services.DeployClearCache>("clearCacheOnServiceUpdateDeployments");
    },
    enumerable: true,
});

