// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Services.Inputs
{

    public sealed class CronJobDetailsArgs : global::Pulumi.ResourceArgs
    {
        [Input("buildPlan", required: true)]
        public Input<string> BuildPlan { get; set; } = null!;

        /// <summary>
        /// Environment (runtime)
        /// </summary>
        [Input("env", required: true)]
        public Input<Pulumi.Render.Services.CronJobDetailsEnv> Env { get; set; } = null!;

        [Input("envSpecificDetails", required: true)]
        public InputUnion<Inputs.DockerDetailsArgs, Inputs.NativeEnvironmentDetailsArgs> EnvSpecificDetails { get; set; } = null!;

        [Input("lastSuccessfulRunAt")]
        public Input<string>? LastSuccessfulRunAt { get; set; }

        /// <summary>
        /// The instance type to use for the preview instance. Note that base services with any paid instance type can't create preview instances with the `free` instance type.
        /// </summary>
        [Input("plan", required: true)]
        public Input<Pulumi.Render.Services.CronJobDetailsPlan> Plan { get; set; } = null!;

        [Input("region", required: true)]
        public Input<Pulumi.Render.Services.CronJobDetailsRegion> Region { get; set; } = null!;

        [Input("schedule", required: true)]
        public Input<string> Schedule { get; set; } = null!;

        public CronJobDetailsArgs()
        {
        }
        public static new CronJobDetailsArgs Empty => new CronJobDetailsArgs();
    }
}
