// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Services.Inputs
{

    /// <summary>
    /// Query params for the API request.
    /// </summary>
    public sealed class ListJobQueryParams : global::Pulumi.InvokeArgs
    {
        [Input("additionalParams")]
        private Dictionary<string, string>? _additionalParams;

        /// <summary>
        /// Additional query params to send with the request that are not defined in the API spec.
        /// </summary>
        public Dictionary<string, string> AdditionalParams
        {
            get => _additionalParams ?? (_additionalParams = new Dictionary<string, string>());
            set => _additionalParams = value;
        }

        /// <summary>
        /// Filter for jobs created after a certain time (specified as an ISO 8601 timestamp)
        /// </summary>
        [Input("createdAfter")]
        public string? CreatedAfter { get; set; }

        /// <summary>
        /// Filter for jobs created before a certain time (specified as an ISO 8601 timestamp)
        /// </summary>
        [Input("createdBefore")]
        public string? CreatedBefore { get; set; }

        /// <summary>
        /// The position in the result list to start from when fetching paginated results. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        /// </summary>
        [Input("cursor")]
        public string? Cursor { get; set; }

        /// <summary>
        /// Filter for jobs finished after a certain time (specified as an ISO 8601 timestamp)
        /// </summary>
        [Input("finishedAfter")]
        public string? FinishedAfter { get; set; }

        /// <summary>
        /// Filter for jobs finished before a certain time (specified as an ISO 8601 timestamp)
        /// </summary>
        [Input("finishedBefore")]
        public string? FinishedBefore { get; set; }

        /// <summary>
        /// The maximum number of items to return. For details, see [Pagination](https://api-docs.render.com/reference/pagination).
        /// </summary>
        [Input("limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// Filter for jobs started after a certain time (specified as an ISO 8601 timestamp)
        /// </summary>
        [Input("startedAfter")]
        public string? StartedAfter { get; set; }

        /// <summary>
        /// Filter for jobs started before a certain time (specified as an ISO 8601 timestamp)
        /// </summary>
        [Input("startedBefore")]
        public string? StartedBefore { get; set; }

        [Input("status")]
        private List<Pulumi.Render.Services.ListJobQueryParamsStatusItem>? _status;

        /// <summary>
        /// Filter for the status of the job (`pending`, `running`, `succeeded`, `failed`, or `canceled`)
        /// </summary>
        public List<Pulumi.Render.Services.ListJobQueryParamsStatusItem> Status
        {
            get => _status ?? (_status = new List<Pulumi.Render.Services.ListJobQueryParamsStatusItem>());
            set => _status = value;
        }

        public ListJobQueryParams()
        {
            Limit = 20;
        }
        public static new ListJobQueryParams Empty => new ListJobQueryParams();
    }
}
