// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.Services.Inputs
{

    public sealed class ServiceWebServiceArgs : Pulumi.ResourceArgs
    {
        [Input("disk")]
        public Input<Inputs.ServiceDiskArgs>? Disk { get; set; }

        [Input("env", required: true)]
        public Input<Pulumi.Render.Services.ServiceWebServiceEnv> Env { get; set; } = null!;

        [Input("envSpecificDetails")]
        public InputUnion<Inputs.ServiceDockerDetailsArgs, Inputs.ServiceNativeEnvironmentDetailsArgs>? EnvSpecificDetails { get; set; }

        [Input("healthCheckPath")]
        public Input<string>? HealthCheckPath { get; set; }

        [Input("numInstances")]
        public Input<double>? NumInstances { get; set; }

        [Input("plan")]
        public Input<Pulumi.Render.Services.ServiceWebServicePlan>? Plan { get; set; }

        [Input("pullRequestPreviewsEnabled")]
        public Input<Pulumi.Render.Services.ServiceWebServicePullRequestPreviewsEnabled>? PullRequestPreviewsEnabled { get; set; }

        [Input("region")]
        public Input<Pulumi.Render.Services.ServiceWebServiceRegion>? Region { get; set; }

        public ServiceWebServiceArgs()
        {
            NumInstances = 1;
            Plan = Pulumi.Render.Services.ServiceWebServicePlan.Starter;
            PullRequestPreviewsEnabled = Pulumi.Render.Services.ServiceWebServicePullRequestPreviewsEnabled.No;
            Region = Pulumi.Render.Services.ServiceWebServiceRegion.Oregon;
        }
    }
}
