// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package blueprints

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-render/sdk/go/render/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListBlueprintSyncs(ctx *pulumi.Context, args *ListBlueprintSyncsArgs, opts ...pulumi.InvokeOption) (*ListBlueprintSyncsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListBlueprintSyncsResult
	err := ctx.Invoke("render:blueprints:listBlueprintSyncs", args.Defaults(), &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListBlueprintSyncsArgs struct {
	// The ID of the Blueprint
	BlueprintId string `pulumi:"blueprintId"`
	// Query params to send with the API request.
	QueryParams *ListBlueprintSyncsQueryParams `pulumi:"queryParams"`
}

// Defaults sets the appropriate defaults for ListBlueprintSyncsArgs
func (val *ListBlueprintSyncsArgs) Defaults() *ListBlueprintSyncsArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.QueryParams = tmp.QueryParams.Defaults()

	return &tmp
}

type ListBlueprintSyncsResult struct {
	Items []SyncWithCursor `pulumi:"items"`
}

func ListBlueprintSyncsOutput(ctx *pulumi.Context, args ListBlueprintSyncsOutputArgs, opts ...pulumi.InvokeOption) ListBlueprintSyncsResultOutput {
	outputArgs := pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) *ListBlueprintSyncsArgs {
			args := v.(ListBlueprintSyncsArgs)
			return args.Defaults()
		})
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("render:blueprints:listBlueprintSyncs", outputArgs, ListBlueprintSyncsResultOutput{}, options).(ListBlueprintSyncsResultOutput)
}

type ListBlueprintSyncsOutputArgs struct {
	// The ID of the Blueprint
	BlueprintId pulumi.StringInput `pulumi:"blueprintId"`
	// Query params to send with the API request.
	QueryParams ListBlueprintSyncsQueryParamsPtrInput `pulumi:"queryParams"`
}

func (ListBlueprintSyncsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListBlueprintSyncsArgs)(nil)).Elem()
}

type ListBlueprintSyncsResultOutput struct{ *pulumi.OutputState }

func (ListBlueprintSyncsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListBlueprintSyncsResult)(nil)).Elem()
}

func (o ListBlueprintSyncsResultOutput) ToListBlueprintSyncsResultOutput() ListBlueprintSyncsResultOutput {
	return o
}

func (o ListBlueprintSyncsResultOutput) ToListBlueprintSyncsResultOutputWithContext(ctx context.Context) ListBlueprintSyncsResultOutput {
	return o
}

func (o ListBlueprintSyncsResultOutput) Items() SyncWithCursorArrayOutput {
	return o.ApplyT(func(v ListBlueprintSyncsResult) []SyncWithCursor { return v.Items }).(SyncWithCursorArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ListBlueprintSyncsResultOutput{})
}
