// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package blueprints

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-render/sdk/go/render/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListBlueprints(ctx *pulumi.Context, args *ListBlueprintsArgs, opts ...pulumi.InvokeOption) (*ListBlueprintsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListBlueprintsResult
	err := ctx.Invoke("render:blueprints:listBlueprints", args.Defaults(), &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListBlueprintsArgs struct {
	// Query params to send with the API request.
	QueryParams *ListBlueprintsQueryParams `pulumi:"queryParams"`
}

// Defaults sets the appropriate defaults for ListBlueprintsArgs
func (val *ListBlueprintsArgs) Defaults() *ListBlueprintsArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.QueryParams = tmp.QueryParams.Defaults()

	return &tmp
}

type ListBlueprintsResult struct {
	Items []BlueprintWithCursor `pulumi:"items"`
}

func ListBlueprintsOutput(ctx *pulumi.Context, args ListBlueprintsOutputArgs, opts ...pulumi.InvokeOption) ListBlueprintsResultOutput {
	outputArgs := pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) *ListBlueprintsArgs {
			args := v.(ListBlueprintsArgs)
			return args.Defaults()
		})
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("render:blueprints:listBlueprints", outputArgs, ListBlueprintsResultOutput{}, options).(ListBlueprintsResultOutput)
}

type ListBlueprintsOutputArgs struct {
	// Query params to send with the API request.
	QueryParams ListBlueprintsQueryParamsPtrInput `pulumi:"queryParams"`
}

func (ListBlueprintsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListBlueprintsArgs)(nil)).Elem()
}

type ListBlueprintsResultOutput struct{ *pulumi.OutputState }

func (ListBlueprintsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListBlueprintsResult)(nil)).Elem()
}

func (o ListBlueprintsResultOutput) ToListBlueprintsResultOutput() ListBlueprintsResultOutput {
	return o
}

func (o ListBlueprintsResultOutput) ToListBlueprintsResultOutputWithContext(ctx context.Context) ListBlueprintsResultOutput {
	return o
}

func (o ListBlueprintsResultOutput) Items() BlueprintWithCursorArrayOutput {
	return o.ApplyT(func(v ListBlueprintsResult) []BlueprintWithCursor { return v.Items }).(BlueprintWithCursorArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ListBlueprintsResultOutput{})
}
