// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registrycredentials

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The registry to use this credential with
type ListRegistryCredentialsQueryParamsTypeItem string

const (
	ListRegistryCredentialsQueryParamsTypeItemGithub         = ListRegistryCredentialsQueryParamsTypeItem("GITHUB")
	ListRegistryCredentialsQueryParamsTypeItemGitlab         = ListRegistryCredentialsQueryParamsTypeItem("GITLAB")
	ListRegistryCredentialsQueryParamsTypeItemDocker         = ListRegistryCredentialsQueryParamsTypeItem("DOCKER")
	ListRegistryCredentialsQueryParamsTypeItemGoogleArtifact = ListRegistryCredentialsQueryParamsTypeItem("GOOGLE_ARTIFACT")
	ListRegistryCredentialsQueryParamsTypeItemAwsEcr         = ListRegistryCredentialsQueryParamsTypeItem("AWS_ECR")
)

func (ListRegistryCredentialsQueryParamsTypeItem) ElementType() reflect.Type {
	return reflect.TypeOf((*ListRegistryCredentialsQueryParamsTypeItem)(nil)).Elem()
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToListRegistryCredentialsQueryParamsTypeItemOutput() ListRegistryCredentialsQueryParamsTypeItemOutput {
	return pulumi.ToOutput(e).(ListRegistryCredentialsQueryParamsTypeItemOutput)
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToListRegistryCredentialsQueryParamsTypeItemOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ListRegistryCredentialsQueryParamsTypeItemOutput)
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToListRegistryCredentialsQueryParamsTypeItemPtrOutput() ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return e.ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(context.Background())
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return ListRegistryCredentialsQueryParamsTypeItem(e).ToListRegistryCredentialsQueryParamsTypeItemOutputWithContext(ctx).ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(ctx)
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ListRegistryCredentialsQueryParamsTypeItem) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ListRegistryCredentialsQueryParamsTypeItemOutput struct{ *pulumi.OutputState }

func (ListRegistryCredentialsQueryParamsTypeItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListRegistryCredentialsQueryParamsTypeItem)(nil)).Elem()
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToListRegistryCredentialsQueryParamsTypeItemOutput() ListRegistryCredentialsQueryParamsTypeItemOutput {
	return o
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToListRegistryCredentialsQueryParamsTypeItemOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemOutput {
	return o
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToListRegistryCredentialsQueryParamsTypeItemPtrOutput() ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return o.ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(context.Background())
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ListRegistryCredentialsQueryParamsTypeItem) *ListRegistryCredentialsQueryParamsTypeItem {
		return &v
	}).(ListRegistryCredentialsQueryParamsTypeItemPtrOutput)
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ListRegistryCredentialsQueryParamsTypeItem) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ListRegistryCredentialsQueryParamsTypeItemOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ListRegistryCredentialsQueryParamsTypeItem) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ListRegistryCredentialsQueryParamsTypeItemPtrOutput struct{ *pulumi.OutputState }

func (ListRegistryCredentialsQueryParamsTypeItemPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ListRegistryCredentialsQueryParamsTypeItem)(nil)).Elem()
}

func (o ListRegistryCredentialsQueryParamsTypeItemPtrOutput) ToListRegistryCredentialsQueryParamsTypeItemPtrOutput() ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return o
}

func (o ListRegistryCredentialsQueryParamsTypeItemPtrOutput) ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return o
}

func (o ListRegistryCredentialsQueryParamsTypeItemPtrOutput) Elem() ListRegistryCredentialsQueryParamsTypeItemOutput {
	return o.ApplyT(func(v *ListRegistryCredentialsQueryParamsTypeItem) ListRegistryCredentialsQueryParamsTypeItem {
		if v != nil {
			return *v
		}
		var ret ListRegistryCredentialsQueryParamsTypeItem
		return ret
	}).(ListRegistryCredentialsQueryParamsTypeItemOutput)
}

func (o ListRegistryCredentialsQueryParamsTypeItemPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ListRegistryCredentialsQueryParamsTypeItemPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ListRegistryCredentialsQueryParamsTypeItem) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ListRegistryCredentialsQueryParamsTypeItemInput is an input type that accepts values of the ListRegistryCredentialsQueryParamsTypeItem enum
// A concrete instance of `ListRegistryCredentialsQueryParamsTypeItemInput` can be one of the following:
//
//	ListRegistryCredentialsQueryParamsTypeItemGithub
//	ListRegistryCredentialsQueryParamsTypeItemGitlab
//	ListRegistryCredentialsQueryParamsTypeItemDocker
//	ListRegistryCredentialsQueryParamsTypeItemGoogleArtifact
//	ListRegistryCredentialsQueryParamsTypeItemAwsEcr
type ListRegistryCredentialsQueryParamsTypeItemInput interface {
	pulumi.Input

	ToListRegistryCredentialsQueryParamsTypeItemOutput() ListRegistryCredentialsQueryParamsTypeItemOutput
	ToListRegistryCredentialsQueryParamsTypeItemOutputWithContext(context.Context) ListRegistryCredentialsQueryParamsTypeItemOutput
}

var listRegistryCredentialsQueryParamsTypeItemPtrType = reflect.TypeOf((**ListRegistryCredentialsQueryParamsTypeItem)(nil)).Elem()

type ListRegistryCredentialsQueryParamsTypeItemPtrInput interface {
	pulumi.Input

	ToListRegistryCredentialsQueryParamsTypeItemPtrOutput() ListRegistryCredentialsQueryParamsTypeItemPtrOutput
	ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(context.Context) ListRegistryCredentialsQueryParamsTypeItemPtrOutput
}

type listRegistryCredentialsQueryParamsTypeItemPtr string

func ListRegistryCredentialsQueryParamsTypeItemPtr(v string) ListRegistryCredentialsQueryParamsTypeItemPtrInput {
	return (*listRegistryCredentialsQueryParamsTypeItemPtr)(&v)
}

func (*listRegistryCredentialsQueryParamsTypeItemPtr) ElementType() reflect.Type {
	return listRegistryCredentialsQueryParamsTypeItemPtrType
}

func (in *listRegistryCredentialsQueryParamsTypeItemPtr) ToListRegistryCredentialsQueryParamsTypeItemPtrOutput() ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return pulumi.ToOutput(in).(ListRegistryCredentialsQueryParamsTypeItemPtrOutput)
}

func (in *listRegistryCredentialsQueryParamsTypeItemPtr) ToListRegistryCredentialsQueryParamsTypeItemPtrOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ListRegistryCredentialsQueryParamsTypeItemPtrOutput)
}

// ListRegistryCredentialsQueryParamsTypeItemArrayInput is an input type that accepts ListRegistryCredentialsQueryParamsTypeItemArray and ListRegistryCredentialsQueryParamsTypeItemArrayOutput values.
// You can construct a concrete instance of `ListRegistryCredentialsQueryParamsTypeItemArrayInput` via:
//
//	ListRegistryCredentialsQueryParamsTypeItemArray{ ListRegistryCredentialsQueryParamsTypeItemArgs{...} }
type ListRegistryCredentialsQueryParamsTypeItemArrayInput interface {
	pulumi.Input

	ToListRegistryCredentialsQueryParamsTypeItemArrayOutput() ListRegistryCredentialsQueryParamsTypeItemArrayOutput
	ToListRegistryCredentialsQueryParamsTypeItemArrayOutputWithContext(context.Context) ListRegistryCredentialsQueryParamsTypeItemArrayOutput
}

type ListRegistryCredentialsQueryParamsTypeItemArray []ListRegistryCredentialsQueryParamsTypeItem

func (ListRegistryCredentialsQueryParamsTypeItemArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ListRegistryCredentialsQueryParamsTypeItem)(nil)).Elem()
}

func (i ListRegistryCredentialsQueryParamsTypeItemArray) ToListRegistryCredentialsQueryParamsTypeItemArrayOutput() ListRegistryCredentialsQueryParamsTypeItemArrayOutput {
	return i.ToListRegistryCredentialsQueryParamsTypeItemArrayOutputWithContext(context.Background())
}

func (i ListRegistryCredentialsQueryParamsTypeItemArray) ToListRegistryCredentialsQueryParamsTypeItemArrayOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ListRegistryCredentialsQueryParamsTypeItemArrayOutput)
}

type ListRegistryCredentialsQueryParamsTypeItemArrayOutput struct{ *pulumi.OutputState }

func (ListRegistryCredentialsQueryParamsTypeItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ListRegistryCredentialsQueryParamsTypeItem)(nil)).Elem()
}

func (o ListRegistryCredentialsQueryParamsTypeItemArrayOutput) ToListRegistryCredentialsQueryParamsTypeItemArrayOutput() ListRegistryCredentialsQueryParamsTypeItemArrayOutput {
	return o
}

func (o ListRegistryCredentialsQueryParamsTypeItemArrayOutput) ToListRegistryCredentialsQueryParamsTypeItemArrayOutputWithContext(ctx context.Context) ListRegistryCredentialsQueryParamsTypeItemArrayOutput {
	return o
}

func (o ListRegistryCredentialsQueryParamsTypeItemArrayOutput) Index(i pulumi.IntInput) ListRegistryCredentialsQueryParamsTypeItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ListRegistryCredentialsQueryParamsTypeItem {
		return vs[0].([]ListRegistryCredentialsQueryParamsTypeItem)[vs[1].(int)]
	}).(ListRegistryCredentialsQueryParamsTypeItemOutput)
}

// The registry to use this credential with
type Registry string

const (
	RegistryGithub         = Registry("GITHUB")
	RegistryGitlab         = Registry("GITLAB")
	RegistryDocker         = Registry("DOCKER")
	RegistryGoogleArtifact = Registry("GOOGLE_ARTIFACT")
	RegistryAwsEcr         = Registry("AWS_ECR")
)

func (Registry) ElementType() reflect.Type {
	return reflect.TypeOf((*Registry)(nil)).Elem()
}

func (e Registry) ToRegistryOutput() RegistryOutput {
	return pulumi.ToOutput(e).(RegistryOutput)
}

func (e Registry) ToRegistryOutputWithContext(ctx context.Context) RegistryOutput {
	return pulumi.ToOutputWithContext(ctx, e).(RegistryOutput)
}

func (e Registry) ToRegistryPtrOutput() RegistryPtrOutput {
	return e.ToRegistryPtrOutputWithContext(context.Background())
}

func (e Registry) ToRegistryPtrOutputWithContext(ctx context.Context) RegistryPtrOutput {
	return Registry(e).ToRegistryOutputWithContext(ctx).ToRegistryPtrOutputWithContext(ctx)
}

func (e Registry) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e Registry) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e Registry) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e Registry) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type RegistryOutput struct{ *pulumi.OutputState }

func (RegistryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Registry)(nil)).Elem()
}

func (o RegistryOutput) ToRegistryOutput() RegistryOutput {
	return o
}

func (o RegistryOutput) ToRegistryOutputWithContext(ctx context.Context) RegistryOutput {
	return o
}

func (o RegistryOutput) ToRegistryPtrOutput() RegistryPtrOutput {
	return o.ToRegistryPtrOutputWithContext(context.Background())
}

func (o RegistryOutput) ToRegistryPtrOutputWithContext(ctx context.Context) RegistryPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Registry) *Registry {
		return &v
	}).(RegistryPtrOutput)
}

func (o RegistryOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RegistryOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Registry) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RegistryOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RegistryOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e Registry) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RegistryPtrOutput struct{ *pulumi.OutputState }

func (RegistryPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Registry)(nil)).Elem()
}

func (o RegistryPtrOutput) ToRegistryPtrOutput() RegistryPtrOutput {
	return o
}

func (o RegistryPtrOutput) ToRegistryPtrOutputWithContext(ctx context.Context) RegistryPtrOutput {
	return o
}

func (o RegistryPtrOutput) Elem() RegistryOutput {
	return o.ApplyT(func(v *Registry) Registry {
		if v != nil {
			return *v
		}
		var ret Registry
		return ret
	}).(RegistryOutput)
}

func (o RegistryPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RegistryPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *Registry) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// RegistryInput is an input type that accepts values of the Registry enum
// A concrete instance of `RegistryInput` can be one of the following:
//
//	RegistryGithub
//	RegistryGitlab
//	RegistryDocker
//	RegistryGoogleArtifact
//	RegistryAwsEcr
type RegistryInput interface {
	pulumi.Input

	ToRegistryOutput() RegistryOutput
	ToRegistryOutputWithContext(context.Context) RegistryOutput
}

var registryPtrType = reflect.TypeOf((**Registry)(nil)).Elem()

type RegistryPtrInput interface {
	pulumi.Input

	ToRegistryPtrOutput() RegistryPtrOutput
	ToRegistryPtrOutputWithContext(context.Context) RegistryPtrOutput
}

type registryPtr string

func RegistryPtr(v string) RegistryPtrInput {
	return (*registryPtr)(&v)
}

func (*registryPtr) ElementType() reflect.Type {
	return registryPtrType
}

func (in *registryPtr) ToRegistryPtrOutput() RegistryPtrOutput {
	return pulumi.ToOutput(in).(RegistryPtrOutput)
}

func (in *registryPtr) ToRegistryPtrOutputWithContext(ctx context.Context) RegistryPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(RegistryPtrOutput)
}

// The registry to use this credential with
type RegistryCredentialRegistry string

const (
	RegistryCredentialRegistryGithub         = RegistryCredentialRegistry("GITHUB")
	RegistryCredentialRegistryGitlab         = RegistryCredentialRegistry("GITLAB")
	RegistryCredentialRegistryDocker         = RegistryCredentialRegistry("DOCKER")
	RegistryCredentialRegistryGoogleArtifact = RegistryCredentialRegistry("GOOGLE_ARTIFACT")
	RegistryCredentialRegistryAwsEcr         = RegistryCredentialRegistry("AWS_ECR")
)

type RegistryCredentialRegistryOutput struct{ *pulumi.OutputState }

func (RegistryCredentialRegistryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RegistryCredentialRegistry)(nil)).Elem()
}

func (o RegistryCredentialRegistryOutput) ToRegistryCredentialRegistryOutput() RegistryCredentialRegistryOutput {
	return o
}

func (o RegistryCredentialRegistryOutput) ToRegistryCredentialRegistryOutputWithContext(ctx context.Context) RegistryCredentialRegistryOutput {
	return o
}

func (o RegistryCredentialRegistryOutput) ToRegistryCredentialRegistryPtrOutput() RegistryCredentialRegistryPtrOutput {
	return o.ToRegistryCredentialRegistryPtrOutputWithContext(context.Background())
}

func (o RegistryCredentialRegistryOutput) ToRegistryCredentialRegistryPtrOutputWithContext(ctx context.Context) RegistryCredentialRegistryPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RegistryCredentialRegistry) *RegistryCredentialRegistry {
		return &v
	}).(RegistryCredentialRegistryPtrOutput)
}

func (o RegistryCredentialRegistryOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o RegistryCredentialRegistryOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RegistryCredentialRegistry) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o RegistryCredentialRegistryOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RegistryCredentialRegistryOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e RegistryCredentialRegistry) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type RegistryCredentialRegistryPtrOutput struct{ *pulumi.OutputState }

func (RegistryCredentialRegistryPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RegistryCredentialRegistry)(nil)).Elem()
}

func (o RegistryCredentialRegistryPtrOutput) ToRegistryCredentialRegistryPtrOutput() RegistryCredentialRegistryPtrOutput {
	return o
}

func (o RegistryCredentialRegistryPtrOutput) ToRegistryCredentialRegistryPtrOutputWithContext(ctx context.Context) RegistryCredentialRegistryPtrOutput {
	return o
}

func (o RegistryCredentialRegistryPtrOutput) Elem() RegistryCredentialRegistryOutput {
	return o.ApplyT(func(v *RegistryCredentialRegistry) RegistryCredentialRegistry {
		if v != nil {
			return *v
		}
		var ret RegistryCredentialRegistry
		return ret
	}).(RegistryCredentialRegistryOutput)
}

func (o RegistryCredentialRegistryPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o RegistryCredentialRegistryPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *RegistryCredentialRegistry) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ListRegistryCredentialsQueryParamsTypeItemInput)(nil)).Elem(), ListRegistryCredentialsQueryParamsTypeItem("GITHUB"))
	pulumi.RegisterInputType(reflect.TypeOf((*ListRegistryCredentialsQueryParamsTypeItemPtrInput)(nil)).Elem(), ListRegistryCredentialsQueryParamsTypeItem("GITHUB"))
	pulumi.RegisterInputType(reflect.TypeOf((*ListRegistryCredentialsQueryParamsTypeItemArrayInput)(nil)).Elem(), ListRegistryCredentialsQueryParamsTypeItemArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegistryInput)(nil)).Elem(), Registry("GITHUB"))
	pulumi.RegisterInputType(reflect.TypeOf((*RegistryPtrInput)(nil)).Elem(), Registry("GITHUB"))
	pulumi.RegisterOutputType(ListRegistryCredentialsQueryParamsTypeItemOutput{})
	pulumi.RegisterOutputType(ListRegistryCredentialsQueryParamsTypeItemPtrOutput{})
	pulumi.RegisterOutputType(ListRegistryCredentialsQueryParamsTypeItemArrayOutput{})
	pulumi.RegisterOutputType(RegistryOutput{})
	pulumi.RegisterOutputType(RegistryPtrOutput{})
	pulumi.RegisterOutputType(RegistryCredentialRegistryOutput{})
	pulumi.RegisterOutputType(RegistryCredentialRegistryPtrOutput{})
}
