// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cronjobs

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-render/sdk/go/render/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

// Query params for the API request.
type RunCronJobCreateQueryParams struct {
	// Additional query params to send with the request that are not defined in the API spec.
	AdditionalParams map[string]string `pulumi:"additionalParams"`
}

// RunCronJobCreateQueryParamsInput is an input type that accepts RunCronJobCreateQueryParamsArgs and RunCronJobCreateQueryParamsOutput values.
// You can construct a concrete instance of `RunCronJobCreateQueryParamsInput` via:
//
//	RunCronJobCreateQueryParamsArgs{...}
type RunCronJobCreateQueryParamsInput interface {
	pulumi.Input

	ToRunCronJobCreateQueryParamsOutput() RunCronJobCreateQueryParamsOutput
	ToRunCronJobCreateQueryParamsOutputWithContext(context.Context) RunCronJobCreateQueryParamsOutput
}

// Query params for the API request.
type RunCronJobCreateQueryParamsArgs struct {
	// Additional query params to send with the request that are not defined in the API spec.
	AdditionalParams pulumi.StringMapInput `pulumi:"additionalParams"`
}

func (RunCronJobCreateQueryParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RunCronJobCreateQueryParams)(nil)).Elem()
}

func (i RunCronJobCreateQueryParamsArgs) ToRunCronJobCreateQueryParamsOutput() RunCronJobCreateQueryParamsOutput {
	return i.ToRunCronJobCreateQueryParamsOutputWithContext(context.Background())
}

func (i RunCronJobCreateQueryParamsArgs) ToRunCronJobCreateQueryParamsOutputWithContext(ctx context.Context) RunCronJobCreateQueryParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RunCronJobCreateQueryParamsOutput)
}

func (i RunCronJobCreateQueryParamsArgs) ToRunCronJobCreateQueryParamsPtrOutput() RunCronJobCreateQueryParamsPtrOutput {
	return i.ToRunCronJobCreateQueryParamsPtrOutputWithContext(context.Background())
}

func (i RunCronJobCreateQueryParamsArgs) ToRunCronJobCreateQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobCreateQueryParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RunCronJobCreateQueryParamsOutput).ToRunCronJobCreateQueryParamsPtrOutputWithContext(ctx)
}

// RunCronJobCreateQueryParamsPtrInput is an input type that accepts RunCronJobCreateQueryParamsArgs, RunCronJobCreateQueryParamsPtr and RunCronJobCreateQueryParamsPtrOutput values.
// You can construct a concrete instance of `RunCronJobCreateQueryParamsPtrInput` via:
//
//	        RunCronJobCreateQueryParamsArgs{...}
//
//	or:
//
//	        nil
type RunCronJobCreateQueryParamsPtrInput interface {
	pulumi.Input

	ToRunCronJobCreateQueryParamsPtrOutput() RunCronJobCreateQueryParamsPtrOutput
	ToRunCronJobCreateQueryParamsPtrOutputWithContext(context.Context) RunCronJobCreateQueryParamsPtrOutput
}

type runCronJobCreateQueryParamsPtrType RunCronJobCreateQueryParamsArgs

func RunCronJobCreateQueryParamsPtr(v *RunCronJobCreateQueryParamsArgs) RunCronJobCreateQueryParamsPtrInput {
	return (*runCronJobCreateQueryParamsPtrType)(v)
}

func (*runCronJobCreateQueryParamsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RunCronJobCreateQueryParams)(nil)).Elem()
}

func (i *runCronJobCreateQueryParamsPtrType) ToRunCronJobCreateQueryParamsPtrOutput() RunCronJobCreateQueryParamsPtrOutput {
	return i.ToRunCronJobCreateQueryParamsPtrOutputWithContext(context.Background())
}

func (i *runCronJobCreateQueryParamsPtrType) ToRunCronJobCreateQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobCreateQueryParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RunCronJobCreateQueryParamsPtrOutput)
}

// Query params for the API request.
type RunCronJobCreateQueryParamsOutput struct{ *pulumi.OutputState }

func (RunCronJobCreateQueryParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RunCronJobCreateQueryParams)(nil)).Elem()
}

func (o RunCronJobCreateQueryParamsOutput) ToRunCronJobCreateQueryParamsOutput() RunCronJobCreateQueryParamsOutput {
	return o
}

func (o RunCronJobCreateQueryParamsOutput) ToRunCronJobCreateQueryParamsOutputWithContext(ctx context.Context) RunCronJobCreateQueryParamsOutput {
	return o
}

func (o RunCronJobCreateQueryParamsOutput) ToRunCronJobCreateQueryParamsPtrOutput() RunCronJobCreateQueryParamsPtrOutput {
	return o.ToRunCronJobCreateQueryParamsPtrOutputWithContext(context.Background())
}

func (o RunCronJobCreateQueryParamsOutput) ToRunCronJobCreateQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobCreateQueryParamsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RunCronJobCreateQueryParams) *RunCronJobCreateQueryParams {
		return &v
	}).(RunCronJobCreateQueryParamsPtrOutput)
}

// Additional query params to send with the request that are not defined in the API spec.
func (o RunCronJobCreateQueryParamsOutput) AdditionalParams() pulumi.StringMapOutput {
	return o.ApplyT(func(v RunCronJobCreateQueryParams) map[string]string { return v.AdditionalParams }).(pulumi.StringMapOutput)
}

type RunCronJobCreateQueryParamsPtrOutput struct{ *pulumi.OutputState }

func (RunCronJobCreateQueryParamsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RunCronJobCreateQueryParams)(nil)).Elem()
}

func (o RunCronJobCreateQueryParamsPtrOutput) ToRunCronJobCreateQueryParamsPtrOutput() RunCronJobCreateQueryParamsPtrOutput {
	return o
}

func (o RunCronJobCreateQueryParamsPtrOutput) ToRunCronJobCreateQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobCreateQueryParamsPtrOutput {
	return o
}

func (o RunCronJobCreateQueryParamsPtrOutput) Elem() RunCronJobCreateQueryParamsOutput {
	return o.ApplyT(func(v *RunCronJobCreateQueryParams) RunCronJobCreateQueryParams {
		if v != nil {
			return *v
		}
		var ret RunCronJobCreateQueryParams
		return ret
	}).(RunCronJobCreateQueryParamsOutput)
}

// Additional query params to send with the request that are not defined in the API spec.
func (o RunCronJobCreateQueryParamsPtrOutput) AdditionalParams() pulumi.StringMapOutput {
	return o.ApplyT(func(v *RunCronJobCreateQueryParams) map[string]string {
		if v == nil {
			return nil
		}
		return v.AdditionalParams
	}).(pulumi.StringMapOutput)
}

// Query params for each of the operations of the resource.
type RunCronJobQueryParams struct {
	// Query params for the create operation.
	Create *RunCronJobCreateQueryParams `pulumi:"create"`
}

// RunCronJobQueryParamsInput is an input type that accepts RunCronJobQueryParamsArgs and RunCronJobQueryParamsOutput values.
// You can construct a concrete instance of `RunCronJobQueryParamsInput` via:
//
//	RunCronJobQueryParamsArgs{...}
type RunCronJobQueryParamsInput interface {
	pulumi.Input

	ToRunCronJobQueryParamsOutput() RunCronJobQueryParamsOutput
	ToRunCronJobQueryParamsOutputWithContext(context.Context) RunCronJobQueryParamsOutput
}

// Query params for each of the operations of the resource.
type RunCronJobQueryParamsArgs struct {
	// Query params for the create operation.
	Create RunCronJobCreateQueryParamsPtrInput `pulumi:"create"`
}

func (RunCronJobQueryParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RunCronJobQueryParams)(nil)).Elem()
}

func (i RunCronJobQueryParamsArgs) ToRunCronJobQueryParamsOutput() RunCronJobQueryParamsOutput {
	return i.ToRunCronJobQueryParamsOutputWithContext(context.Background())
}

func (i RunCronJobQueryParamsArgs) ToRunCronJobQueryParamsOutputWithContext(ctx context.Context) RunCronJobQueryParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RunCronJobQueryParamsOutput)
}

func (i RunCronJobQueryParamsArgs) ToRunCronJobQueryParamsPtrOutput() RunCronJobQueryParamsPtrOutput {
	return i.ToRunCronJobQueryParamsPtrOutputWithContext(context.Background())
}

func (i RunCronJobQueryParamsArgs) ToRunCronJobQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobQueryParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RunCronJobQueryParamsOutput).ToRunCronJobQueryParamsPtrOutputWithContext(ctx)
}

// RunCronJobQueryParamsPtrInput is an input type that accepts RunCronJobQueryParamsArgs, RunCronJobQueryParamsPtr and RunCronJobQueryParamsPtrOutput values.
// You can construct a concrete instance of `RunCronJobQueryParamsPtrInput` via:
//
//	        RunCronJobQueryParamsArgs{...}
//
//	or:
//
//	        nil
type RunCronJobQueryParamsPtrInput interface {
	pulumi.Input

	ToRunCronJobQueryParamsPtrOutput() RunCronJobQueryParamsPtrOutput
	ToRunCronJobQueryParamsPtrOutputWithContext(context.Context) RunCronJobQueryParamsPtrOutput
}

type runCronJobQueryParamsPtrType RunCronJobQueryParamsArgs

func RunCronJobQueryParamsPtr(v *RunCronJobQueryParamsArgs) RunCronJobQueryParamsPtrInput {
	return (*runCronJobQueryParamsPtrType)(v)
}

func (*runCronJobQueryParamsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RunCronJobQueryParams)(nil)).Elem()
}

func (i *runCronJobQueryParamsPtrType) ToRunCronJobQueryParamsPtrOutput() RunCronJobQueryParamsPtrOutput {
	return i.ToRunCronJobQueryParamsPtrOutputWithContext(context.Background())
}

func (i *runCronJobQueryParamsPtrType) ToRunCronJobQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobQueryParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RunCronJobQueryParamsPtrOutput)
}

// Query params for each of the operations of the resource.
type RunCronJobQueryParamsOutput struct{ *pulumi.OutputState }

func (RunCronJobQueryParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RunCronJobQueryParams)(nil)).Elem()
}

func (o RunCronJobQueryParamsOutput) ToRunCronJobQueryParamsOutput() RunCronJobQueryParamsOutput {
	return o
}

func (o RunCronJobQueryParamsOutput) ToRunCronJobQueryParamsOutputWithContext(ctx context.Context) RunCronJobQueryParamsOutput {
	return o
}

func (o RunCronJobQueryParamsOutput) ToRunCronJobQueryParamsPtrOutput() RunCronJobQueryParamsPtrOutput {
	return o.ToRunCronJobQueryParamsPtrOutputWithContext(context.Background())
}

func (o RunCronJobQueryParamsOutput) ToRunCronJobQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobQueryParamsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RunCronJobQueryParams) *RunCronJobQueryParams {
		return &v
	}).(RunCronJobQueryParamsPtrOutput)
}

// Query params for the create operation.
func (o RunCronJobQueryParamsOutput) Create() RunCronJobCreateQueryParamsPtrOutput {
	return o.ApplyT(func(v RunCronJobQueryParams) *RunCronJobCreateQueryParams { return v.Create }).(RunCronJobCreateQueryParamsPtrOutput)
}

type RunCronJobQueryParamsPtrOutput struct{ *pulumi.OutputState }

func (RunCronJobQueryParamsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RunCronJobQueryParams)(nil)).Elem()
}

func (o RunCronJobQueryParamsPtrOutput) ToRunCronJobQueryParamsPtrOutput() RunCronJobQueryParamsPtrOutput {
	return o
}

func (o RunCronJobQueryParamsPtrOutput) ToRunCronJobQueryParamsPtrOutputWithContext(ctx context.Context) RunCronJobQueryParamsPtrOutput {
	return o
}

func (o RunCronJobQueryParamsPtrOutput) Elem() RunCronJobQueryParamsOutput {
	return o.ApplyT(func(v *RunCronJobQueryParams) RunCronJobQueryParams {
		if v != nil {
			return *v
		}
		var ret RunCronJobQueryParams
		return ret
	}).(RunCronJobQueryParamsOutput)
}

// Query params for the create operation.
func (o RunCronJobQueryParamsPtrOutput) Create() RunCronJobCreateQueryParamsPtrOutput {
	return o.ApplyT(func(v *RunCronJobQueryParams) *RunCronJobCreateQueryParams {
		if v == nil {
			return nil
		}
		return v.Create
	}).(RunCronJobCreateQueryParamsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RunCronJobCreateQueryParamsInput)(nil)).Elem(), RunCronJobCreateQueryParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RunCronJobCreateQueryParamsPtrInput)(nil)).Elem(), RunCronJobCreateQueryParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RunCronJobQueryParamsInput)(nil)).Elem(), RunCronJobQueryParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RunCronJobQueryParamsPtrInput)(nil)).Elem(), RunCronJobQueryParamsArgs{})
	pulumi.RegisterOutputType(RunCronJobCreateQueryParamsOutput{})
	pulumi.RegisterOutputType(RunCronJobCreateQueryParamsPtrOutput{})
	pulumi.RegisterOutputType(RunCronJobQueryParamsOutput{})
	pulumi.RegisterOutputType(RunCronJobQueryParamsPtrOutput{})
}
