// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class Environment extends pulumi.CustomResource {
    /**
     * Get an existing Environment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Environment {
        return new Environment(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'render:environments:Environment';

    /**
     * Returns true if the given object is an instance of Environment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Environment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Environment.__pulumiType;
    }

    public /*out*/ readonly databasesIds!: pulumi.Output<string[]>;
    public /*out*/ readonly envGroupIds!: pulumi.Output<string[]>;
    public readonly name!: pulumi.Output<string>;
    /**
     * Indicates whether network connections across environments are allowed.
     */
    public readonly networkIsolationEnabled!: pulumi.Output<boolean>;
    public readonly projectId!: pulumi.Output<string>;
    /**
     * Indicates whether an environment is `unprotected` or `protected`. Only admin users can perform destructive actions in `protected` environments.
     */
    public readonly protectedStatus!: pulumi.Output<enums.environments.ProtectedStatus>;
    public /*out*/ readonly redisIds!: pulumi.Output<string[]>;
    public /*out*/ readonly serviceIds!: pulumi.Output<string[]>;

    /**
     * Create a Environment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EnvironmentArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["networkIsolationEnabled"] = args?.networkIsolationEnabled;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["protectedStatus"] = args?.protectedStatus;
            resourceInputs["databasesIds"] = undefined /*out*/;
            resourceInputs["envGroupIds"] = undefined /*out*/;
            resourceInputs["redisIds"] = undefined /*out*/;
            resourceInputs["serviceIds"] = undefined /*out*/;
        } else {
            resourceInputs["databasesIds"] = undefined /*out*/;
            resourceInputs["envGroupIds"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkIsolationEnabled"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["protectedStatus"] = undefined /*out*/;
            resourceInputs["redisIds"] = undefined /*out*/;
            resourceInputs["serviceIds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Environment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Environment resource.
 */
export interface EnvironmentArgs {
    name?: pulumi.Input<string>;
    /**
     * Indicates whether network connections across environments are allowed.
     */
    networkIsolationEnabled?: pulumi.Input<boolean>;
    projectId: pulumi.Input<string>;
    /**
     * Indicates whether an environment is `unprotected` or `protected`. Only admin users can perform destructive actions in `protected` environments.
     */
    protectedStatus?: pulumi.Input<enums.environments.ProtectedStatus>;
}
