// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listRegistryCredentials(args?: ListRegistryCredentialsArgs, opts?: pulumi.InvokeOptions): Promise<ListRegistryCredentialsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("render:registrycredentials:listRegistryCredentials", {
    }, opts);
}

export interface ListRegistryCredentialsArgs {
}

export interface ListRegistryCredentialsResult {
    readonly items: outputs.registrycredentials.RegistryCredential[];
}
export function listRegistryCredentialsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListRegistryCredentialsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("render:registrycredentials:listRegistryCredentials", {
    }, opts);
}

