// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Render.KeyValue.Outputs
{

    [OutputType]
    public sealed class RedisDetailpropertiesmaintenance
    {
        public readonly string Id;
        /// <summary>
        /// If present, the maintenance run cannot be scheduled for later than this date-time.
        /// </summary>
        public readonly string? PendingMaintenanceBy;
        public readonly string ScheduledAt;
        public readonly Pulumi.Render.KeyValue.RedisDetailpropertiesmaintenanceState State;
        public readonly string Type;

        [OutputConstructor]
        private RedisDetailpropertiesmaintenance(
            string id,

            string? pendingMaintenanceBy,

            string scheduledAt,

            Pulumi.Render.KeyValue.RedisDetailpropertiesmaintenanceState state,

            string type)
        {
            Id = id;
            PendingMaintenanceBy = pendingMaintenanceBy;
            ScheduledAt = scheduledAt;
            State = state;
            Type = type;
        }
    }
}
